--Bug 6904146  parallel hint ignored with high number of columns on 11.2.0.2




SELECT /*+ PARALLEL(T,4) */ * FROM (
SELECT /*+  ALL_ROWS PARALLEL(acct,4) PARALLEL(bnkr_case,1) */
'FDE',
acct.acct_id acct_id,
acct.relt_id relt_id,
acct.sor_id sor_id,
NVL (acct.sor_run, acct.sor_id) sor_run,
NVL (acct.agen_cd, ' ') agen_cd,
bk.amt_past_due amt_past_due,
0 rtc_ltr_bal,
0 rtc_ltr_amt_past_due,
0 rtc_ltr_delq_grade_ind,
0 rtc_ltr_rstrct_st_ind,
0 rtc_ltr_dys_past_due,
NULL au,
bk.auto_dr_ind auto_dr_ind,
bk.bal bal,
NVL(bk.behavior_score, 0) behavior_score,
bk.bill_cyc bill_cyc,
DECODE ((NVL (SUBSTR (bk.bk_stat_cd, 1, 1), ' ') ||
LPAD (NVL (TO_CHAR (bk.stat_lst_chg_rsn_cd), ' '), 2, '0')),
' 00', ' ',
(NVL (SUBSTR (bk.bk_stat_cd, 1, 1), ' ') ||
LPAD (NVL (TO_CHAR (bk.stat_lst_chg_rsn_cd), ' '), 2, '0')))
bk_stat_cd,
NULL bnk_num,
NVL (bk.bnkr_cd, ' ') bnkr_cd,
NULL br_num,
bk.chrg_off_dt chrg_off_dt,
NULL chrg_off_rsn_cd,
bk.cirm_score cirm_score,
NULL cl_cd,
bk.cline cline,
' ' coll_cd,
NULL conv_id,
NULL ctp_rsn_cd,
NULL ctp_stat_cd,
NVL(ent_summary_agen.curr_fico_score, 0) curr_fico_score,
NULL cust_num,
NULL dlr_num,
bk.dys_past_bill_dt dys_past_bill_dt,
DECODE(acct.dept_id,
801,
NVL(k_fde_acct.f_get_fde_dys_past_due(acct.acct_id,NVL(bk.dys_past_due, 0)),0),
bk.dys_past_due) dys_past_due,
NULL dys_past_mat_dt,
bk.fraud_cd fraud_cd,
NULL gl_cd,
acct.grp_id grp_id,
NULL hvc_cd,
NULL int_due_dt,
row_number() over(partition by acct.acct_id order by acct.acct_id) ln_num,
NVL(acct.lst_ltr_dt,TO_DATE('01/01/1900', 'MM/DD/YYYY'))
lst_ltr_dt,
bk.lst_pmt_amt lst_pmt_amt,
NVL(bk.lst_pmt_dt,TO_DATE('01/01/1900', 'MM/DD/YYYY'))
lst_pmt_dt,
bk.min_pmt min_pmt,
bk.num_cyc_delq num_cyc_delq,
NULL obgn_stat_cd,
NULL obgn_type,
NULL officer_cd,
NULL or_cd,
bk.opn_dt orig_dt,
NVL(ent_summary_agen.orig_fico_score, 0) orig_fico_score,
bk.overlimit_pct overlimit_pct,
acct.ph_quality_id ph_quality_id,
NULL pmt_due_dy,
bk.prev_cyc_delq prev_cyc_delq,
NVL(bk.user_cd_1,' ') prim_cltrl_cd,
NULL prmt_cd,
bk.prod_id prod_id,
NVL (cra.prog_cd, ' ') prog_cd,
LTRIM (RTRIM (bk.rau)) rau,
NULL rcse_cd,
acct.recent_cntct_dt recent_cntct_dt,
NULL recovery_cd,
NULL rmo_xfr_officer_num,
DECODE (acct.dept_id,
801, NVL(acct.rndm_num,0),
TO_NUMBER (bk.rndm_dgt)) rndm_num,
NULL shaw_acct_cd,
NULL short_nm,
NVL (zip.st_cd, ' ') st_cd,
NULL svc_unit,
NVL (zip.tm_zone, ' ') tm_zone,
NULL vip_cd,
RPAD (bk.zip, 5) zip,
NULL nw_prmt_cd,
NULL orig_st_cd,
NVL (bk.acq_cd, ' ') acq_cd,
NULL cel_cd,
NVL(zip.rural_ak_ind, 0) rural_ak_ind,
NVL (bk.agnt_cd, ' ') agnt_cd,
NULL note_rating,
NULL most_delq_acct_ind,
NULL adv_delq_stat_cd_1,
NULL adv_delq_stat_cd_2,
NULL adv_delq_stat_cd_3,
NULL adv_delq_stat_cd_4,
NULL adv_delq_stat_cd_5,
NULL adv_delq_stat_cd_6,
NULL cntrctl_dys_past_due,
NULL cntrctl_pd_to_plus_amt,
NULL co_cd,
NULL correspond_cd,
NULL delq_cond,
NVL(ent_summary_acct.language_cd,' ') language_cd,
NULL regn_num,
NVL(bk.str_orig, 0) str_orig,
NULL str_mktg,
NULL str_svc,
NULL mrtg_num,
NULL stra_score,
NULL delq_ind,
0 coll_score,
NULL grp_cd,
NULL regn_cd,
NVL (bk.collector_cd, ' ') collector_cd,
NULL prmt_grp_id,
NULL nw_prmt_grp_id,
NULL orig_chan_cd,
NULL bnk_ctrl_rec_prod_cd,
NULL prvsnl_chrg_off_resv_amt,
NULL net_bnk_asset_val,
NULL end_of_draw_dt,
NULL disp_cd,
NULL num_of_pmts,
NVL(risk_force.recovery_score, 0) recovery_score,
DECODE (bk.chrg_off_dt, NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - bk.chrg_off_dt)
dys_snc_chrg_off,
NULL nsf_ind,
TO_NUMBER(TO_CHAR(TO_DATE('05/21/2013','mm/dd/yyyy'),'DD')) dy_of_mo,
NVL(agen.agen_id, 0) agen_id,
NVL(acct.prev_agen_id, 0) prev_agen_id,
NULL lgl_stat_cd,
CASE
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_pmt_dt
ELSE 99999
END dys_snc_lst_pmt,
NULL payoff_amt_ins,
NVL(bk.fde_hvc_cd, ' ') fde_hvc_cd,
NVL(bnkr_case.payoff_calc_ind, 0) payoff_calc_ind,
bnkr_case.pro_se_ind pro_se_ind,
-- this case statement reproduces the logic in k_bnkr.f_prejudicial.
-- calculating the prejudicial indicator this way as opposed to using the
-- function speeds up NOPS by 10 minutes(+) on the WFF critical path
CASE WHEN bnkr_case.case_id IS NULL
THEN
0
WHEN bnkr_case.dt_filed IS NULL
THEN
0
WHEN
bk.opn_dt IS NULL
THEN
0
WHEN prod_lookup.bnkr_ln_ind = 1
AND bnkr_case.dt_filed BETWEEN bk.opn_dt AND (bk.opn_dt + 90)
THEN
1
WHEN prod_lookup.bnkr_ln_ind != 1
AND bnkr_case.dt_filed BETWEEN bk.opn_dt AND (bk.opn_dt + 70)
THEN
1
ELSE
0
END prejudicial_ind,
NVL(bnkr_case.payoff_bnkr_case_pmt_srce_cd, ' ')
payoff_bnkr_case_pmt_srce_cd,
DECODE (bnkr_case.dt_filed,
NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - bnkr_case.dt_filed), 0),
99999))
dys_snc_bnkr_case_filed,
-- bnkr_court_dist_ent_id is populated subsequently
0 bnkr_court_dist_ent_id,
NVL(bnkr_case.mnl_bnkr_ind,0) mnl_bnkr_ind,
-- cmty_prop_ind is populated subsequently
0 cmty_prop_ind,
NULL invst_pool,
NULL num_of_ext,
bk.pricing_stra pricing_stra,
NULL expir_dt,
NULL yom_forced_rsn_cd,
0 coll_score_2,
0 coll_score_3,
0 coll_score_4,
0 coll_score_5,
0 coll_score_6,
NVL(risk_force.rndm_num_2,0) rndm_num_2,
NVL(risk_force.rndm_num_3,0) rndm_num_3,
NVL(risk_force.rndm_num_4,0) rndm_num_4,
NVL(risk_force.rndm_num_5,0) rndm_num_5,
NVL(risk_force.rndm_num_6,0) rndm_num_6,
NVL(risk_force.treatmnt_num,'00000000') treatmnt_num,
NULL write_dn_ind,
NULL wffbc_acct_type_cd,
NULL overlimit_amt,
NULL anl_fee_amt,
NULL wffbc_bnk_num,
NVL(risk_force.bnkr_score,0) bnkr_score,
NVL(bk.ins_ind, 0) ccrd_ins_ind,
NULL wffbc_cr_rating_cd,
NULL dys_overlimit,
DECODE (bk.lst_nsf_dt, NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_nsf_dt) dys_snc_lst_nsf_dt,
NULL dlr_at_risk,
NULL ltv_pct,
NULL num_of_accts,
NULL risk_attrition_score,
NULL risk_coll_score,
NULL test_dgt_num,
NULL wffbc_srce_cd,
NULL wffbc_queue_nm,
NULL language_id,
NVL(coll_score.risk_proba_chrg_off_score, ' ') risk_proba_chrg_off_score,
NVL(coll_score.risk_stra_1_score, ' ') risk_stra_1_score,
NVL(coll_score.risk_stra_2_score, ' ') risk_stra_2_score,
NULL dl_stra_score,
NVL(coll_score.recovery_stra_1_score,' ') recovery_stra_1_score,
NVL(coll_score.recovery_stra_2_score,' ') recovery_stra_2_score,
NULL override_prejudicial_id,
NVL(acct.addr_quality_id, 0) addr_quality_id,
NVL(acct.skip_cntct_ind, 0) skip_cntct_ind,
GREATEST(
LEAST(NVL(forcls.sale_dt,TO_DATE('05/21/2013','mm/dd/yyyy'))-
NVL(forcls.list_dt,TO_DATE('05/21/2013','mm/dd/yyyy')),9999),-9999) dys_on_mkt,
NULL portfl_cd,
DECODE(bk.dys_past_due,
NULL, 0,
bk.dys_past_due +
LAST_DAY(TO_DATE('05/21/2013','mm/dd/yyyy')) - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_past_due_eom,
NVL(recovery.recovery_stat_id, 0) recovery_stat_id,
NVL(recovery.recovery_stat_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) recovery_stat_dt,
NVL(acct.dept_id,0) dept_id,
recovery_req.recovery_req_type_id recovery_req_type_id,
recovery_req.recovery_req_rsn_id recovery_req_rsn_id,
recovery_req.dec_stat_id dec_stat_id,
recovery.hld_from_agen_until_dt hld_from_agen_until_dt,
recovery_settle.recovery_settle_stat_id recovery_settle_stat_id,
NVL(agen_tran.agen_tran_cd, ' ') agen_tran_cd,
NVL(recovery_agen_evnt_a.recovery_agen_evnt_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) recovery_agen_evnt_dt,
NULL wffrs_clnt_num,
NULL wffrs_agen_cd,
NULL wffrs_chrg_off_rsn_cd,
NULL wffrs_chrg_off_rule_id,
NULL stmt_not_sent_ind,
NVL(bk.rcse_ind,0) rcse_ind,
NULL wffrs_category_cd,
NULL wffrs_industry_cd,
TO_CHAR(NVL(bnkr_case.chapter,0)) chapter,
NULL co_borr_fico_score,
NULL cutoff_dy,
NULL wffrs_risk_stat_cd,
bnkr_case.case_id case_id,
CASE
WHEN acct.agen_asn_dt IS NOT NULL
AND bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(acct.agen_asn_dt, bk.lst_pmt_dt)
WHEN acct.agen_asn_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(acct.agen_asn_dt)
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.lst_pmt_dt)
ELSE 999999
END dys_snc_lst_pmt_snc_agen_asn,
CASE
WHEN bk.chrg_off_dt IS NOT NULL
AND bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.chrg_off_dt, bk.lst_pmt_dt)
WHEN bk.chrg_off_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.chrg_off_dt)
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.lst_pmt_dt)
ELSE 999999
END dys_snc_lst_pmt_snc_chrg_off,
NULL led_bnk_ind,
NULL dys_snc_cutoff_dy,
NULL wffrs_sys_cd,
NULL wffrs_dlr_id,
NULL wffrs_delq_stat_cd,
recovery_settle.settle_amt settle_amt,
DECODE (recovery_agen_evnt_a.recovery_agen_evnt_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - recovery_agen_evnt_a.recovery_agen_evnt_dt)
dys_snc_agen_evnt,
DECODE (recovery.recovery_stat_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - recovery.recovery_stat_dt)
dys_snc_recovery_stat_chg,
NULL overlimit_scenario_score,
NULL wffrs_ins_cd,
NULL opn_dt,
bk.cacs_user_routing cacs_user_routing,
bk.bal payoff_amt_bal,
NVL(dstr_desc_lkup.dstr_type_id,0) dstr_type_id,
NVL(dstr.dstr_desc_id,0) dstr_desc_id,
NVL(dstr_impact_lvl_lkup.dstr_impact_lvl_val,0) dstr_impact_lvl_id,
NULL reaff_risk_stat_cd,
NULL wffrs_clsd_stat_cd_prim,
NULL wffrs_clsd_stat_cd_scndry,
NULL shaw_acct_cat_cd,
NULL acct_in_feed_ind,
NVL(acct.chrg_off_type_id,0) chrg_off_type_id, -- default to full if charged off
bnkr_case.bnkr_mtch_cd bnkr_mtch_cd,
bnkr_case.agen_ntc_type_cd agen_ntc_type_cd,
NULL dys_until_cutoff_dy,
NULL fis_delq_cl_cd,
NULL fis_mn_cd,
NULL fis_org_cd,
NULL fis_anal_stop_cd,
NULL fis_bad_chk_stop_cd,
NULL fis_disb_stop_cd,
NULL fis_forcls_stop_cd,
NULL fis_no_ntc_stop_cd,
NULL fis_pd_in_full_stop_cd,
NULL fis_proc_stop_cd,
NULL tot_amt_due,
NVL(real_estate.real_estate_prop_type_cd, ' ')
real_estate_prop_type_cd,
NVL(forcls.forcls_stat_id, 0) forcls_stat_id,
NULL dys_until_no_ntc_stop_expir_dt,
NULL dys_until_proc_stop_expir_dt,
DECODE
(coll_act.dir_asst_cntct_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.dir_asst_cntct_dt) dys_snc_dir_asst_cntct_dt,
DECODE
(coll_act.cust_info_dda_ver_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.cust_info_dda_ver_dt)
dys_snc_cust_info_dda_ver_dt,
DECODE
(coll_act.vend_srch_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.vend_srch_dt) dys_snc_vend_srch_dt,
DECODE
(coll_act.empnt_ver_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.empnt_ver_dt) dys_snc_empnt_ver_dt,
DECODE
(coll_act.other_acct_rvw_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.other_acct_rvw_dt) dys_snc_other_acct_rvw_dt,
0 dys_past_cccs_pmt_due_dt,
DECODE
(coll_act.arch_srch_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.arch_srch_dt) dys_snc_arch_srch_dt,
DECODE (forcls.sr_sale_bid_dt,
NULL, 99999,
forcls.sr_sale_bid_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_sr_sale_bid_dt,
DECODE (forcls.sr_sale_dt,
NULL, 99999,
forcls.sr_sale_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_sr_sale_dt,
NVL(forcls.third_party_sale_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) third_party_sale_dt,
NVL(forcls.forcls_resume_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) forcls_resume_dt,
NVL(forcls.sr_sale_bid_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) sr_sale_bid_dt,
NVL(forcls.sr_sale_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) sr_sale_dt,
DECODE
(forcls.third_party_sale_dt,
NULL, 99999,
forcls.third_party_sale_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_third_party_sale_dt,
DECODE
(forcls.forcls_resume_dt,
NULL, 99999,
forcls.forcls_resume_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_forcls_resume_dt,
0 coll_scenario_score,
' ' fis_bnkr_workstn_stat_cd,
' ' fis_forcls_workstn_stat_cd,
' ' loss_mitigat_workstn_stat_cd,
' ' fis_invst_type_cd,
' ' fis_sscra_cd,
NVL(acct_pre_queue_atr.call_center_agen_asn_ind,0)
call_center_agen_asn_ind,
NVL2(acct_pre_queue_atr.call_center_agen_unasn_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.call_center_agen_unasn_dt, 0)
dys_snc_call_center_agen_unasn,
NVL2(acct_pre_queue_atr.max_call_center_agen_asn_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.max_call_center_agen_asn_dt, 0)
dys_snc_call_center_agen_asn,
NVL(coll_score.risk_pricing_updt_dt,
TO_DATE('01/01/1900','MM/DD/YYYY')) risk_pricing_updt_dt,
NVL(coll_score.srm_behavior_score,' ') srm_behavior_score,
NVL(coll_score.risk_pricing_cd,' ') risk_pricing_cd,
NVL(coll_score.risk_pricing_curr_int_rt,0) risk_pricing_curr_int_rt,
NVL(coll_score.risk_pricing_orig_int_rt, 0) risk_pricing_orig_int_rt,
NVL(coll_score.risk_pricing_orig_cr_lmt_amt, 0) risk_pricing_orig_cr_lmt_amt,
NVL(coll_score.risk_pricing_curr_cr_lmt_amt, 0) risk_pricing_curr_cr_lmt_amt,
NVL(coll_score.risk_pricing_hi_risk_flg_score, ' ') risk_pricing_hi_risk_flg_score,
NVL(coll_score.risk_pricing_strght_rolr_score, ' ') risk_pricing_strght_rolr_score,
NVL(coll_score.risk_pricing_frbr_score, ' ') risk_pricing_frbr_score,
NVL(coll_score.risk_pricing_lgl_score, ' ') risk_pricing_lgl_score,
NVL(forcls.attorney_refd_dt, TO_DATE('01/01/1900', 'mm/dd/yyyy'))
attorney_refd_dt,
NVL(bk.csh_int_rt,0) csh_int_rt,
NVL(bk.chrg_off_amt,0) chrg_off_amt,
NVL(bk.closure_dt, TO_DATE('01/01/1900', 'mm/dd/yyyy'))
closure_dt,
NVL(bk.int_rate,0) int_rate,
NVL(bk.merchandise_int_rt,0) merchandise_int_rt,
NVL(bk.overlimit_amt,0) fde_overlimit_amt,
CASE WHEN acct.dept_id = 801
THEN
CASE WHEN bk.bk_stat_cd = 'Z'
THEN
NVL(bk.amt_past_due, 0)
ELSE
NVL(bk.tot_amt_due, 0)
END
ELSE
NVL(bk.tot_amt_due, 0)
END fde_tot_amt_due,
NVL(risk_force.coll_score_cd_1,0) coll_score_cd_1,
NVL(risk_force.coll_score_cd_2,0) coll_score_cd_2,
NVL(risk_force.coll_score_cd_3,0) coll_score_cd_3,
NVL(risk_force.coll_score_cd_4,0) coll_score_cd_4,
NVL(risk_force.coll_score_cd_5,0) coll_score_cd_5,
NVL(risk_force.coll_score_cd_6,0) coll_score_cd_6,
NVL(risk_force.rndm_num_1,0) rndm_num_1,
0 recover_corp_adv_bal_amt,
0 nsf_fee_amt,
0 lte_fee_amt,
0 other_fee_amt,
0 susp_bal_amt,
NVL(coll_score.call_score, 0) call_score,
NVL(coll_score.hld_out_stra_cd, ' ') hld_out_stra_cd,
NVL(coll_score.no_call_score, 0) no_call_score,
NVL(coll_score.strght_rolr_stra_cd, ' ') strght_rolr_stra_cd,
NVL(coll_score.triad_rndm_num, ' ') triad_rndm_num,
NVL(coll_score.triad_scenario_score, ' ') triad_scenario_score,
NVL(coll_score.triad_stra_score, ' ') triad_stra_score,
NVL(coll_score.triad_treatmnt_num, ' ') triad_treatmnt_num,
0 elig_for_ext_reage,
0 dys_snc_arm_frst_pmt_dt,
0 dys_until_arm_frst_pmt_dt,
0 adj_rt_mrtg_ind,
0 dys_snc_int_rt_strt_dt,
0 dys_snc_int_rt_end_dt,
0 int_rt,
0 pmt_amt,
0 dys_snc_prev_int_rt_strt_dt,
0 dys_snc_prev_int_rt_end_dt,
0 prev_int_rt,
0 prev_pmt_amt,
0 dys_until_next_int_rt_chg_dt,
0 dys_until_next_pmt_chg_dt,
0 next_int_rt,
0 next_pmt_amt,
0 dys_until_nxt_reset_dt,
0 dys_until_frst_reset_dt,
0 num_of_pmts_past_due,
0 mo_past_due_num,
' ' fis_prior_svcr_cd,
0 benft_req_stat_id,
0 benft_req_type_id,
' ' shaw_ins_prod_cd_prot_plan,
' ' shaw_ins_stat_cd_prot_plan,
NVL2(spcl_hdlg.dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - trunc(spcl_hdlg.dt), 0) dys_snc_cccs_pps_accpt,
NVL(bk.stat_lst_chg_rsn_cd,0) stat_lst_chg_rsn_cd,
NVL(ent_summary_agen.curr_fico_score,0) bur_score,
NVL(bk.cacs_rsn_cd,' ') cacs_rsn_cd,
NVL(bk.fix_pmt_amt,0) fix_pmt_amt,
NVL(bk.prom_to_pay_ind,0) prom_to_pay_ind,
NVL(bk.mtch_pay_prog_ind,0) mtch_pay_prog_ind,
NVL(bk.react_prog_ind,0) react_prog_ind,
NVL(bk.pre_bnkr_ind,'0') pre_bnkr_ind,
NVL(risk_force.fdebc_risk_stat_cd,'0') risk_stat_cd,
NVL(risk_force.adaptation_score,0) adaptation_score,
NVL(risk_force.ermc_score,' ') ermc_score,
NVL(risk_force.attrition_score,0) attrition_score,
NVL(bk.prev_bk_stat_cd,' ') prev_bk_stat_cd,
NVL(bk.corp_nm,' ') corp_nm,
NVL(bk.clnt_num,' ') clnt_num,
DECODE(bk.bill_cyc, NULL, 0,
TO_NUMBER(TO_CHAR(TO_DATE('05/21/2013','mm/dd/yyyy') - bk.bill_cyc,'DD')))
dys_snc_bill_cyc,
NVL(bk.coll_cd,0) fde_coll_cd,
NVL(bk.lst_stmt_dt,to_date('01/01/1900', 'mm/dd/yyyy'))
lst_stmt_dt,
' ' alpha_type,
0 defr_int_bal,
0 tot_defr_int_bal,
NVL(risk_force.fut_treatmnt_int_rt,0) fut_treatmnt_int_rt,
NVL(risk_force.fut_treatmnt_pmt_amt,0) fut_treatmnt_pmt_amt,
LEAST(GREATEST(DECODE
(acct.last_right_cntct_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct.last_right_cntct_dt),0),99999) dys_snc_right_party_cntct,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_frst_pmt_dt,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_shaw_rschd_dt,
0 cccs_pps_act_ind,
' ' cccs_pps_stat_desc,
' ' cccs_pps_agen_nm,
' ' cccs_pps_agen_cd,
0 cccs_pps_nxt_pmt_no,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_pps_nxt_pmt_dt,
NVL(acct.buyer_ent_id, 0) buyer_ent_id,
NVL(acct.cell_ph_consent_no_ind,0) cell_ph_consent_no_ind,
NVL(acct.cell_ph_consent_unknown_ind,0) cell_ph_consent_unknown_ind,
NVL(acct.cell_ph_consent_yes_ind,0) cell_ph_consent_yes_ind,
NVL(rstrc.rstrc_stat_id, 0) rstrc_stat_id,
NVL(bnkr_case.due_amt_pst_arrears_trustee,0) due_amt_pst_arrears_trustee,
NVL(bnkr_case.due_amt_pst_arrears_direct,0) due_amt_pst_arrears_direct,
NVL(bnkr_case.due_amt_pre_arrears_direct,0) due_amt_pre_arrears_direct,
NVL(bnkr_case.due_amt_pre_arrears_trustee,0) due_amt_pre_arrears_trustee,
NVL(bnkr_case.due_amt_secured_direct,0) due_amt_secured_direct,
NVL(bnkr_case.due_amt_secured_trustee,0) due_amt_secured_trustee,
NVL(bnkr_case.due_amt_unsecured_direct,0) due_amt_unsecured_direct,
NVL(bnkr_case.due_amt_unsecured_trustee,0) due_amt_unsecured_trustee,
NVL(bnkr_case.bal_amt_pst_arrears_direct,0) bal_amt_pst_arrears_direct,
NVL(bnkr_case.bal_amt_pst_arrears_trustee,0) bal_amt_pst_arrears_trustee,
NVL(bnkr_case.bal_amt_pre_arrears_direct,0) bal_amt_pre_arrears_direct,
NVL(bnkr_case.bal_amt_pre_arrears_trustee,0) bal_amt_pre_arrears_trustee,
NVL(bnkr_case.bal_amt_secured_direct,0) bal_amt_secured_direct,
NVL(bnkr_case.bal_amt_secured_trustee,0) bal_amt_secured_trustee,
NVL(bnkr_case.bal_amt_unsecured_direct,0) bal_amt_unsecured_direct,
NVL(bnkr_case.bal_amt_unsecured_trustee,0) bal_amt_unsecured_trustee,
NVL(bnkr_case.plan_amt_pst_arrears_direct,0) plan_amt_pst_arrears_direct,
NVL(bnkr_case.plan_amt_pst_arrears_trustee,0) plan_amt_pst_arrears_trustee,
NVL(bnkr_case.plan_amt_pre_arrears_direct,0) plan_amt_pre_arrears_direct,
NVL(bnkr_case.plan_amt_pre_arrears_trustee,0) plan_amt_pre_arrears_trustee,
NVL(bnkr_case.plan_amt_secured_direct,0) plan_amt_secured_direct,
NVL(bnkr_case.plan_amt_secured_trustee,0) plan_amt_secured_trustee,
NVL(bnkr_case.plan_amt_unsecured_direct,0) plan_amt_unsecured_direct,
NVL(bnkr_case.plan_amt_unsecured_trustee,0) plan_amt_unsecured_trustee,
LEAST(GREATEST(DECODE(bnkr_case.pst_petition_pd_to_dt_direct,
NULL,99999,
SYSDATE - bnkr_case.pst_petition_pd_to_dt_direct),0),99999)
dys_snc_pst_peti_pd_to_dt_dir,
LEAST(GREATEST(DECODE(bnkr_case.pst_petition_pd_to_dt_trustee,
NULL,99999,
SYSDATE - bnkr_case.pst_petition_pd_to_dt_trustee),0),99999)
dys_snc_pst_peti_pd_to_dt_trus,
NVL(bnkr_case.prin_bal_pst_arrears_direct,0) prin_bal_pst_arrears_direct,
NVL(bnkr_case.prin_bal_pst_arrears_trustee,0) prin_bal_pst_arrears_trustee,
NVL(bnkr_case.prin_bal_pre_arrears_direct,0) prin_bal_pre_arrears_direct,
NVL(bnkr_case.prin_bal_pre_arrears_trustee,0) prin_bal_pre_arrears_trustee,
NVL(bnkr_case.prin_bal_secured_direct,0) prin_bal_secured_direct,
NVL(bnkr_case.prin_bal_secured_trustee,0) prin_bal_secured_trustee,
NVL(bnkr_case.prin_bal_unsecured_direct,0) prin_bal_unsecured_direct,
NVL(bnkr_case.prin_bal_unsecured_trustee,0) prin_bal_unsecured_trustee,
NVL(real_estate.real_estate_mkt_cond_id,0) real_estate_mkt_cond_id,
0 ext_reage_dec_id,
0 dys_snc_dsn_dt,
0 ext_reage_dec_rsn_id,
0 ext_reage_stat_id,
NVL(ext_reage_2.mitigat_plan_type_id,0) mitigat_plan_type_id,
0 dys_snc_new_matur_dt,
0 hld_cd,
0 hm_price_idx_val,
0 fmly_payoff_amt_prin,
0 fmly_net_bnk_asset_val,
0 fmly_payoff_amt_int,
0 fmly_curr_pmt,
0 fmly_tot_amt_due,
99999 fmly_borr_next_due_in_dys,
0 fmly_dly_weigh_avg_int_rt,
LEAST(GREATEST(DECODE(dstr.dstr_dt,
NULL,99999,
SYSDATE - dstr.dstr_dt),0),99999) dys_snc_dstr_dt,
LEAST(GREATEST(DECODE(dstr.relief_prd_expir_dt,
NULL,99999,
SYSDATE - dstr.relief_prd_expir_dt),0),99999)
dys_snc_relief_prd_expir_dt,
NVL(bk.mrchnt_num,' ') mrchnt_num,
NVL(bk.fde_industry_cd,' ') industry_cd,
NVL(bk.sys_cd,' ') sys_cd,
NVL(risk_force.risk_atr_1,'0') risk_atr_1,
NVL(risk_force.risk_atr_2,'0') risk_atr_2,
NVL(risk_force.risk_atr_3,'0') risk_atr_3,
NVL(risk_force.risk_atr_4,'0') risk_atr_4,
NVL(risk_force.risk_atr_5,'0') risk_atr_5,
NVL(risk_force.risk_atr_6,'0') risk_atr_6,
NVL(risk_force.risk_atr_7,'0') risk_atr_7,
NVL(risk_force.risk_atr_8,'0') risk_atr_8,
NVL(risk_force.risk_atr_9,'0') risk_atr_9,
NVL(risk_force.risk_atr_10,'0') risk_atr_10,
NVL(risk_force.msa_cd,'0') msa_cd,
NVL(risk_force.cbsa_cd,'0') cbsa_cd,
NVL(risk_force.ud_1_cd,0) ud_1_cd,
NVL(risk_force.ud_2_cd,0) ud_2_cd,
NVL(risk_force.ud_3_cd,0) ud_3_cd,
NVL(risk_force.ud_4_cd,0) ud_4_cd,
NVL(bk.prin_cd,' ') prin_cd,
0 curr_due_amt,
0 avm_hm_appr_val,
' ' cr_line_mgmt_cd,
0 user_def_coll_stra_proba_pct_1,
0 user_def_coll_stra_proba_pct_2,
0 user_def_coll_stra_proba_pct_3,
0 user_def_coll_stra_proba_pct_4,
0 user_def_coll_stra_proba_pct_5,
0 user_def_coll_stra_score_1,
0 user_def_coll_stra_score_2,
0 user_def_coll_stra_score_3,
0 user_def_coll_stra_score_4,
0 user_def_coll_stra_score_5,
0 user_def_coll_stra_amt_1,
0 user_def_coll_stra_amt_2,
0 user_def_coll_stra_amt_3,
' ' user_def_coll_stra_cd_1,
' ' user_def_coll_stra_cd_2,
' ' user_def_coll_stra_cd_3,
' ' user_def_coll_stra_cd_4,
' ' user_def_coll_stra_cd_5,
' ' user_def_coll_stra_cd_6,
' ' user_def_coll_stra_cd_7,
TO_DATE('01/01/1900', 'mm/dd/yyyy') chrg_off_dec_stat_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') equity_anal_compl_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') sr_ver_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') tax_chk_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') tax_due_dt,
0 delq_tax,
0 tax_pd_thru_escrow_ind,
TO_DATE('01/01/1900', 'MM/DD/YYYY') mcod_dt,
0 mcod_stream_id,
' ' pool_ins_cd,
' ' pool_ins_claim_stat_cd,
0 dys_snc_full_chrg_off_dt,
NVL(ent_summary_acct.curr_fico_score,' ') risk_curr_fico_score,
NVL(ent_summary_acct.orig_fico_score,' ') risk_orig_fico_score,
NVL(bk.acct_typ_cd,' ') acct_typ_cd,
' ' sch_cd,
' ' prod_desc,
' ' prod_cd,
' ' city,
' ' ph_num,
TO_DATE('01/01/1900', 'MM/DD/YYYY') def_forb_end_dt,
' ' defer_grp_cd,
0 cosign_present_ind,
' ' frst_pmt_dflt_cd,
TO_DATE('01/01/1900', 'MM/DD/YYYY') curr_pmt_due_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') orig_contract_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') disb_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') left_school_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') grad_dt,
0 grace_period_dys,
TO_DATE('01/01/1900', 'MM/DD/YYYY') separation_dt,
' ' earn_learn_stat_cd,
0 fraud_ind,
0 cease_desist_ind,
0 deceased_ind,
TO_DATE('01/01/1900', 'MM/DD/YYYY') judg_dt,
' ' lgl_st_cd,
0 ln_dischrg_ind,
' ' acct_srce_cd,
' ' recovery_collector_cd,
' ' prod_typ_cd,
' ' bnk_cd,
NVL (real_estate.prop_cond_id, 0) prop_cond_id,
NVL (real_estate.prop_occ_stat_id, 0) prop_occ_stat_id,
NVL (acct.hamp_fallout_rsn_id, 0) hamp_fallout_rsn_id,
acct.hamp_fallout_rsn_dt hamp_fallout_rsn_dt,
NVL2(acct.hamp_fallout_rsn_dt, TO_DATE('05/21/2013','mm/dd/yyyy')
- acct.hamp_fallout_rsn_dt, 0) dys_snc_hamp_fallout_rsn_dt,
NVL(bk.user_pricing_cd,' ') user_pricing_cd,
NVL(bk.fde_srce_cd,' ') fde_srce_cd,
0 treatmnt_num_1,
0 treatmnt_num_2,
0 treatmnt_num_3,
0 treatmnt_num_4,
0 treatmnt_num_5,
0 treatmnt_num_6,
TO_DATE('01/01/1900','mm/dd/yyyy') sr_expir_dt,
0 outstdg_bal_ind,
0 outstdg_bal_amt ,
NULL non_rcvd_order_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') todays_dt,
0 max_appr_val,
NULL ignr_prev_bpo_notneedavail_ind,
NULL ignr_prev_intr_bpo_ind,
NULL intr_bpo_exists_ind,
NULL bpo_notneedavail_exists_ind,
NULL coll_addr_1,
NULL coll_city,
NULL coll_st_cd,
NULL coll_zip,
NULL coll_apn_num,
NULL cncl_fut_bpo_cd,
NULL east_ind,
' ' efs_correspond_cd,
0 pst_petition_debt_ind,
TO_DATE('01/01/1900','mm/dd/yyyy') lgl_stip_dt,
NVL(acct_pre_queue_atr.pre_lqdtn_bal, 0) pre_lqdtn_bal,
NVL(acct_pre_queue_atr.lqdtn_amt_pstd, 0) lqdtn_amt_pstd,
NVL(acct_pre_queue_atr.debt_outstdg_amt, 0) debt_outstdg_amt,
0 bnkr_ind,
0 recon_dec_ind,
TO_DATE('01/01/1900','mm/dd/yyyy') recon_dec_dt,
0 dlgt_auth_lvl,
TO_DATE('01/01/1900','mm/dd/yyyy') recon_compl_dt,
NVL(
(CASE
WHEN bk.chrg_off_dt IS NOT NULL
THEN
CASE WHEN bk.lst_pmt_dt IS NOT NULL
AND bk.lst_pmt_dt > bk.chrg_off_dt
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_pmt_dt
END
END),0) dys_snc_pst_chrg_off_pmt,
NVL(bk.non_acrl_cd,' ') non_acrl_cd,
' ' afs_rsn_stat_cd,
NVL(ent_summary_acct.cr_rpt_fico_score,0) cr_rpt_fico_score_borr,
NVL(ent_summary_acct.cr_rpt_dt,
TO_DATE('01/01/1900','mm/dd/yyyy')) cr_rpt_dt_borr,
' ' str_orig_st_cd,
0 cr_rpt_fico_score_co_borr,
TO_DATE('01/01/1900','mm/dd/yyyy') cr_rpt_dt_co_borr,
0 po_box_ind_borr,
0 po_box_ind_co_borr,
0 frbr_ind,
NVL(bk.sic_fde_industry_id,0) sic_fde_industry_id,
NVL(bk.sic_industry_id,0) sic_industry_id,
0 cell_ph_rating_unknown_ind,
NVL(acct.cell_ph_ver_consent_yes_ind_1,0) cell_ph_ver_consent_yes_ind_1,
NVL(acct.cell_ph_ver_consent_yes_ind_2,0) cell_ph_ver_consent_yes_ind_2,
NVL(acct.spoc_asn_stat_id,0) spoc_asn_stat_id,
NVL(acct.spoc_asn_rsn_id,0) spoc_asn_rsn_id,
DECODE(spoc_asn_stat.spoc_act_ind,
NULL,0,
spoc_asn_stat.spoc_act_ind) spoc_act_ind,
NVL(acct.spoc_login_cd,' ') spoc_login_cd,
NULL dys_snc_rvw_dt,
NVL(bk.fde_acct_language_cd,' ') fde_acct_language_cd,
0 scra_elig_ind,
NVL(bk.fdebc_nowline_lien_stat_cd, ' ') fdebc_nowline_lien_stat_cd,
DECODE(bk.reage_dt,
NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - bk.reage_dt), 0), 99999))
dys_snc_lst_reage_dt,
NVL(bk.tot_reage_hist, 0) tot_reage_hist,
DECODE
(acct_mil_svc.act_duty_start_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.act_duty_start_dt))
dys_snc_act_duty_start_dt,
DECODE
(acct_mil_svc.act_duty_end_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.act_duty_end_dt))
dys_snc_act_duty_end_dt,
DECODE
(acct_mil_svc.order_rcv_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.order_rcv_dt))
dys_snc_order_rcv_dt,
NVL(forcls.forcls_outsource_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) forcls_outsource_dt,
DECODE (acct.cntct_stra_email_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_email_dt), 0), 99999))
dys_snc_cntct_stra_email_dt,
DECODE (acct.cntct_stra_txt_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_txt_dt), 0), 99999))
dys_snc_cntct_stra_txt_dt,
DECODE (acct.cntct_stra_imd_pre_auth_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_imd_pre_auth_dt), 0), 99999))
dys_snc_cntct_stra_pre_auth_dt,
DECODE (acct.cntct_stra_imd_pre_impt_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_imd_pre_impt_dt), 0), 99999))
dys_snc_cntct_stra_pre_impt_dt,
DECODE (acct.cntct_stra_misc_1_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_1_dt), 0), 99999))
dys_snc_cntct_stra_misc_1_dt,
DECODE (acct.cntct_stra_misc_2_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_2_dt), 0), 99999))
dys_snc_cntct_stra_misc_2_dt,
DECODE (acct.cntct_stra_misc_3_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_3_dt), 0), 99999))
dys_snc_cntct_stra_misc_3_dt,
DECODE (acct.cntct_stra_misc_4_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_4_dt), 0), 99999))
dys_snc_cntct_stra_misc_4_dt,
DECODE (acct.cntct_stra_sor_ltr_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_sor_ltr_dt), 0), 99999))
dys_snc_cntct_stra_sor_ltr_dt,
NULL mrtg_portfl_cd,
NULL fis_acct_num,
NULL msp_clnt_num,
settle.settle_stat_id settle_stat_id,
DECODE (settle.next_settle_pmt_due_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(settle.next_settle_pmt_due_dt))
dys_snc_next_settle_pmt_due,
DECODE (lgl_pre_asn.lgl_dec_dt,
NULL,
99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(lgl_pre_asn.lgl_dec_dt)), 0), 99999))
dys_snc_lgl_dec_dt,
NVL(chrg_off_dec.chrg_off_dec_stat_id,0) chrg_off_dec_stat_id,
real_estate.vesting vesting,
DECODE (real_estate.deed_of_trust_chk_dt,
NULL,
99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - real_estate.deed_of_trust_chk_dt), 0), 99999))
dys_snc_deed_of_trust_chk_dt,
real_estate.county_rec county_rec,
' ' spcl_alloc_ind_num,
NVL(acct.cell_ph_consent_not_yes_ind,0) cell_ph_consent_not_yes_ind,
0 cell_ph_consent_not_no_ind,
DECODE(acct_ent_acct.cntct_type_id, 1, NVL(ent_summary_acct.liable_ind, 0), 0) borr_liable_ind,
0 co_signer_1_liable_ind,
0 co_signer_2_liable_ind,
0 co_signer_3_liable_ind,
0 student_liable_ind,
' ' co_signer_1_state,
' ' co_signer_2_state,
' ' co_signer_3_state,
' ' student_state,
' ' co_signer_1_efs_correspond_cd,
' ' co_signer_2_efs_correspond_cd,
' ' co_signer_3_efs_correspond_cd,
' ' student_efs_correspond_cd,
' ' eodrw_proc_cd,
' ' eodrw_ltr_90_cd,
' ' eodrw_ltr_60_cd,
' ' eodrw_ltr_30_cd,
' ' eodrw_ltr_final_cd,
' ' mat_ltr_90_cd,
' ' mat_ltr_60_cd,
' ' mat_ltr_30_cd,
' ' real_estate_prop_type_cd_orig,
' ' cltrl_st_cd,
risk_force.mis_atr_num_1 mis_atr_num_1,
risk_force.mis_atr_num_2 mis_atr_num_2,
risk_force.mis_atr_num_3 mis_atr_num_3,
risk_force.mis_atr_num_4 mis_atr_num_4,
risk_force.mis_atr_num_5 mis_atr_num_5,
risk_force.mis_atr_num_6 mis_atr_num_6,
risk_force.mis_atr_num_7 mis_atr_num_7,
risk_force.mis_atr_num_8 mis_atr_num_8,
risk_force.mis_atr_num_9 mis_atr_num_9,
risk_force.mis_atr_num_10 mis_atr_num_10,
risk_force.mis_atr_num_11 mis_atr_num_11,
risk_force.mis_atr_num_12 mis_atr_num_12,
risk_force.mis_atr_num_13 mis_atr_num_13,
risk_force.mis_atr_num_14 mis_atr_num_14,
risk_force.mis_atr_num_15 mis_atr_num_15,
risk_force.mis_atr_num_16 mis_atr_num_16,
risk_force.mis_atr_num_17 mis_atr_num_17,
risk_force.mis_atr_num_18 mis_atr_num_18,
risk_force.mis_atr_num_19 mis_atr_num_19,
risk_force.mis_atr_num_20 mis_atr_num_20,
risk_force.mis_atr_num_21 mis_atr_num_21,
risk_force.mis_atr_num_22 mis_atr_num_22,
risk_force.mis_atr_num_23 mis_atr_num_23,
risk_force.mis_atr_num_24 mis_atr_num_24,
risk_force.mis_atr_num_25 mis_atr_num_25,
risk_force.mis_atr_num_26 mis_atr_num_26,
risk_force.mis_atr_num_27 mis_atr_num_27,
risk_force.mis_atr_num_28 mis_atr_num_28,
risk_force.mis_atr_num_29 mis_atr_num_29,
risk_force.mis_atr_num_30 mis_atr_num_30,
risk_force.mis_atr_num_31 mis_atr_num_31,
risk_force.mis_atr_num_32 mis_atr_num_32,
risk_force.mis_atr_num_33 mis_atr_num_33,
risk_force.mis_atr_num_34 mis_atr_num_34,
risk_force.mis_atr_num_35 mis_atr_num_35,
risk_force.mis_atr_num_36 mis_atr_num_36,
risk_force.mis_atr_num_37 mis_atr_num_37,
risk_force.mis_atr_num_38 mis_atr_num_38,
risk_force.mis_atr_num_39 mis_atr_num_39,
risk_force.mis_atr_num_40 mis_atr_num_40,
risk_force.mis_atr_num_41 mis_atr_num_41,
risk_force.mis_atr_dt_1 mis_atr_dt_1,
risk_force.mis_atr_dt_2 mis_atr_dt_2,
risk_force.mis_atr_dt_3 mis_atr_dt_3,
risk_force.mis_atr_txt_1 mis_atr_txt_1,
risk_force.mis_atr_txt_2 mis_atr_txt_2,
risk_force.mis_atr_txt_3 mis_atr_txt_3,
risk_force.mis_atr_amt_1 mis_atr_amt_1,
risk_force.mis_atr_amt_2 mis_atr_amt_2,
risk_force.mis_atr_amt_3 mis_atr_amt_3,
NVL(bk.auth_flg_cd,' ') auth_flg_cd,
NVL(acct.no_dl_permission,0) no_dl_permission,
NVL(bk.internal_stat_cd,' ') internal_stat_cd,
SUBSTR(bk.bk_acct_num,-2,2) lst_2_dgt_acct_num,
SUBSTR(bk.misc_fld_7,7,1) misc_fld_7_pos_7,
SUBSTR(bk.bk_acct_num,-1,1) lst_dgt_acct_num,
NVL(bk.stmt_hld_cd,' ') stmt_hld_cd,
NVL(bk.cr_bur_cd,' ') cr_bur_rpt_cd,
bk.delq_amt_cyc5 delq_amt_cyc5,
bk.delq_amt_cyc6 delq_amt_cyc6,
bk.delq_amt_cyc7 delq_amt_cyc7,
NULL dys_past_due_360,
0 lst_3_dgt_acct_num,
' ' lst_tran_cd,
0 dys_lst_mont_tran,
0 cltrl_cnt,
NVL(acct_pre_queue_atr.chk_by_ph_pmt_delq_cyc_5_ind, 0) chk_by_ph_pmt_delq_cyc_5_ind,
NVL(acct_pre_queue_atr.vca_prom_amt_delq_cyc_5_ind, 0) vca_prom_amt_delq_cyc_5_ind,
NVL(acct_pre_queue_atr.chk_by_ph_pmt_delq_cyc_7_ind, 0) chk_by_ph_pmt_delq_cyc_7_ind,
NVL(acct_pre_queue_atr.vca_prom_amt_delq_cyc_7_ind, 0) vca_prom_amt_delq_cyc_7_ind,
DECODE (acct_pre_queue_atr.dys_snc_lst_ma_cntct_ltr_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.dys_snc_lst_ma_cntct_ltr_dt)
dys_snc_lst_ma_cntct_ltr_dt,
DECODE (acct.rtc_ltr_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct.rtc_ltr_dt ) dys_snc_lst_cure_dt,
acct_pre_queue_atr.lst_cure_ltr_st_cd lst_cure_ltr_st_cd,
acct_pre_queue_atr.cnt_cure_ltr_snc_lst_365_dys cnt_cure_ltr_snc_lst_365_dys,
SUBSTR(bk.misc_fld_7,4,1) misc_fld_7_pos_4,
SUBSTR(bk.misc_fld_7,1,1) misc_fld_7_pos_1,
bk.ins_ind ins_ind,
bk.life_ins_prod_cd life_ins_prod_cd,
bk.chrg_off_exc_cd chrg_off_exc_cd,
bk.spcl_flg_5_cd spcl_flg_5_cd,
bk.spcl_flg_6_cd spcl_flg_6_cd,
bk.spcl_flg_8_cd spcl_flg_8_cd,
DECODE (acct_pre_queue_atr.dys_snc_right_time_pmt_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.dys_snc_right_time_pmt_dt )
dys_snc_right_time_pmt_dt,
DECODE (acct_pre_queue_atr.settle_expir_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.settle_expir_dt)
settle_expir_dt,
DECODE (acct_pre_queue_atr.judg_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.judg_dt)
dys_snc_judg_dt,
DECODE (acct_pre_queue_atr.renewal_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.renewal_dt)
renewal_dt,
DECODE (acct_pre_queue_atr.orig_judg_exp_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.orig_judg_exp_dt)
orig_judg_exp_dt,
DECODE (acct_pre_queue_atr.renewal_final_exp_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.renewal_final_exp_dt)
renewal_final_exp_dt
FROM t_acct_fde_nops_queue acct,
t_bnkr_case bnkr_case,
t_bk bk,
t_acct_ent acct_ent_acct,
t_acct_ent acct_ent_agen,
t_agen_ent agen,
t_cra_lookup cra,
t_zip_lookup zip,
t_agen_tran agen_tran,
t_recovery recovery,
t_recovery_req recovery_req,
t_recovery_agen_evnt recovery_agen_evnt_a,
(SELECT *
FROM t_recovery_settle
WHERE (acct_id, recovery_settle_id) IN
(SELECT acct_id, MAX(recovery_settle_id) recovery_settle_id
FROM t_recovery_settle
GROUP BY acct_id)) recovery_settle,
(SELECT acct_id,
MAX(reco_agen_evnt.agen_tran_id) agen_tran_id
FROM t_recovery_agen reco_agen,
t_recovery_agen_evnt reco_agen_evnt
WHERE reco_agen.recovery_agen_id = reco_agen_evnt.recovery_agen_id
GROUP BY reco_agen.acct_id) recovery_agen_evnt_b,
t_acct_cltrl acct_cltrl,
t_forcls forcls,
t_prod_lookup prod_lookup,
t_real_estate real_estate,
t_acct_coll_act coll_act,
t_acct_pre_queue_atr PARTITION(NOPS) acct_pre_queue_atr,
t_risk_force risk_force,
t_ent_summary ent_summary_acct,
t_ent_summary ent_summary_agen,
t_ln_spcl_hdlg_stat spcl_hdlg,
t_dstr_desc_lookup dstr_desc_lkup,
t_dstr_impact_lvl_lookup dstr_impact_lvl_lkup,
(select * from t_dstr where prim_ind = 1) dstr,
t_rstrc rstrc,
t_rstrc_acct rstrc_acct,
t_coll_stra_score coll_score,
(select rank () over (partition by acct_id
order by req_dt, ext_reage_id desc nulls last) rank,
ext_reage.acct_id acct_id,
ext_reage.ext_reage_dec_id ext_reage_dec_id,
ext_reage.dec_dt dec_dt,
ext_reage.ext_reage_dec_rsn_id ext_reage_dec_rsn_id,
ext_reage.ext_reage_stat_id ext_reage_stat_id,
ext_reage.mitigat_plan_type_id mitigat_plan_type_id,
ext_reage.new_mat_dt new_mat_dt
from yo.t_ext_reage ext_reage
) ext_reage_2,
t_acct_mil_svc acct_mil_svc,
t_spoc_asn_stat_lkp spoc_asn_stat,
t_lgl_pre_asn lgl_pre_asn,
(SELECT acct_id, expir_dt,chrg_off_dec_stat_id
FROM t_chrg_off_dec
WHERE (acct_id, chrg_off_dec_id) in
(SELECT acct_id, MAX(chrg_off_dec_id)
FROM t_chrg_off_dec
WHERE expir_dt > TRUNC(SYSDATE)
GROUP BY ACCT_ID)) chrg_off_dec,
t_settle_stat_lkp settle_stat,
t_settle settle
WHERE cra.cra_cd (+) = bk.cra_cd
AND zip.zip (+) = bk.zip
AND prod_lookup.prod_id (+) = bk.prod_id
AND bk.acct_id = acct.acct_id
AND agen_tran.agen_tran_id (+) = recovery_agen_evnt_a.agen_tran_id
AND bk.acct_id = recovery.acct_id(+)
AND recovery.curr_recovery_req_id = recovery_req.recovery_req_id (+)
AND recovery_settle.acct_id (+) = recovery.acct_id
AND recovery_agen_evnt_b.acct_id (+) = recovery.acct_id
AND bnkr_case.acct_id (+) = acct.acct_id
AND bnkr_case.prim_ind (+) = 1
AND recovery_agen_evnt_b.agen_tran_id = recovery_agen_evnt_a.agen_tran_id (+)
AND acct.sys_stat_id <> 6
AND acct.sor_id = 2
AND acct_ent_acct.acct_id (+) = acct.acct_id
AND acct_ent_acct.cntct_type_id (+) = 1
AND acct_ent_agen.acct_id (+) = acct.acct_id
AND acct_ent_agen.cntct_type_id (+) = 203
AND agen.ent_id (+) = acct_ent_agen.ent_id
AND acct_cltrl.acct_id (+) = acct.acct_id
AND acct_cltrl.prim_ind (+) = 1
AND acct_cltrl.cltrl_id = forcls.cltrl_id (+)
AND acct_cltrl.cltrl_id = real_estate.cltrl_id (+)
AND coll_act.acct_id (+) = acct.acct_id
AND acct_pre_queue_atr.acct_id (+) = acct.acct_id
AND acct_pre_queue_atr.acct_id (+) = acct.acct_id
AND risk_force.acct_id (+) = acct.acct_id
AND ent_summary_acct.ent_id (+) = acct_ent_acct.ent_id
AND ent_summary_agen.ent_id (+) = acct_ent_agen.ent_id
AND spcl_hdlg.acct_id (+) = acct.acct_id
AND spcl_hdlg.spcl_hdlg_stat_id (+) = 3087
AND spcl_hdlg.spcl_hdlg_stat_set_id (+) = 3087
AND dstr.acct_id (+) = acct.acct_id
AND dstr_desc_lkup.dstr_desc_id (+) = dstr.dstr_desc_id
AND dstr_impact_lvl_lkup.dstr_impact_lvl_id (+) = dstr_desc_lkup.dstr_impact_lvl_id
AND rstrc.rstrc_id (+) = rstrc_acct.rstrc_id
AND rstrc_acct.acct_id (+) = acct.acct_id
AND coll_score.acct_id (+) = acct.acct_id
AND ext_reage_2.acct_id (+) = acct.acct_id
AND ext_reage_2.rank (+) = 1
AND acct_mil_svc.acct_id (+) = acct.acct_id
AND acct_mil_svc.prim_ind (+) = 1
AND spoc_asn_stat.spoc_asn_stat_id (+) = acct.spoc_asn_stat_id
AND lgl_pre_asn.acct_id (+) = acct.acct_id
AND chrg_off_dec.acct_id (+) = acct.acct_id
AND settle_stat.settle_stat_id (+) = settle.settle_stat_id
AND settle.acct_id (+) = acct.acct_id
) T WHERE t.ln_num=1;

SQL> select
  2    decode(px.qcinst_id,NULL,username,
  3          ' - '||lower(substr(s.program,length(s.program)-4,4) ) ) "Username",
  4    decode(px.qcinst_id,NULL, 'QC', '(Slave)') "QC/Slave" ,
  5    to_char( px.server_set) "Slave Set",
  6    to_char(s.sid) "SID",
  7    decode(px.qcinst_id, NULL ,to_char(s.sid) ,px.qcsid) "QC SID",
  8    px.req_degree "Requested DOP",
  9    px.degree "Actual DOP"
 10  from
 11    v$px_session px,
 12    v$session s
 13  where
 14    px.sid=s.sid (+)
 15   and
 16    px.serial#=s.serial#
 17  order by 5 , 1 desc
 18  /

Username     QC/Slave   Slave Set  SID                                      QC SID Requested DOP Actual DOP
------------ ---------- ---------- ---------------------------------------- ------ ------------- ----------
YO           QC                    3301                                     3301
 - p007      (Slave)    2          10816                                    3301               4       4
 - p006      (Slave)    2          10350                                    3301               4       4
 - p005      (Slave)    2          9874                                     3301               4       4
 - p004      (Slave)    2          9406                                     3301               4       4
 - p003      (Slave)    1          8946                                     3301               4       4
 - p002      (Slave)    1          8475                                     3301               4       4
 - p001      (Slave)    1          8001                                     3301               4       4
 - p000      (Slave)    1          7530                                     3301               4       4

9 rows selected.






SELECT /*+ PARALLEL(T,4) */ * FROM (
SELECT /*+  ALL_ROWS PARALLEL(acct,4) PARALLEL(bnkr_case,1) */
'FDE',
acct.acct_id acct_id,
acct.relt_id relt_id,
acct.sor_id sor_id,
NVL (acct.sor_run, acct.sor_id) sor_run,
NVL (acct.agen_cd, ' ') agen_cd,
bk.amt_past_due amt_past_due,
0 rtc_ltr_bal,
0 rtc_ltr_amt_past_due,
0 rtc_ltr_delq_grade_ind,
0 rtc_ltr_rstrct_st_ind,
0 rtc_ltr_dys_past_due,
NULL au,
bk.auto_dr_ind auto_dr_ind,
bk.bal bal,
NVL(bk.behavior_score, 0) behavior_score,
bk.bill_cyc bill_cyc,
DECODE ((NVL (SUBSTR (bk.bk_stat_cd, 1, 1), ' ') ||
LPAD (NVL (TO_CHAR (bk.stat_lst_chg_rsn_cd), ' '), 2, '0')),
' 00', ' ',
(NVL (SUBSTR (bk.bk_stat_cd, 1, 1), ' ') ||
LPAD (NVL (TO_CHAR (bk.stat_lst_chg_rsn_cd), ' '), 2, '0')))
bk_stat_cd,
NULL bnk_num,
NVL (bk.bnkr_cd, ' ') bnkr_cd,
NULL br_num,
bk.chrg_off_dt chrg_off_dt,
NULL chrg_off_rsn_cd,
bk.cirm_score cirm_score,
NULL cl_cd,
bk.cline cline,
' ' coll_cd,
NULL conv_id,
NULL ctp_rsn_cd,
NULL ctp_stat_cd,
NVL(ent_summary_agen.curr_fico_score, 0) curr_fico_score,
NULL cust_num,
NULL dlr_num,
bk.dys_past_bill_dt dys_past_bill_dt,
DECODE(acct.dept_id,
801,
NVL(k_fde_acct.f_get_fde_dys_past_due(acct.acct_id,NVL(bk.dys_past_due, 0)),0),
bk.dys_past_due) dys_past_due,
NULL dys_past_mat_dt,
bk.fraud_cd fraud_cd,
NULL gl_cd,
acct.grp_id grp_id,
NULL hvc_cd,
NULL int_due_dt,
row_number() over(partition by acct.acct_id order by acct.acct_id) ln_num,
NVL(acct.lst_ltr_dt,TO_DATE('01/01/1900', 'MM/DD/YYYY'))
lst_ltr_dt,
bk.lst_pmt_amt lst_pmt_amt,
NVL(bk.lst_pmt_dt,TO_DATE('01/01/1900', 'MM/DD/YYYY'))
lst_pmt_dt,
bk.min_pmt min_pmt,
bk.num_cyc_delq num_cyc_delq,
NULL obgn_stat_cd,
NULL obgn_type,
NULL officer_cd,
NULL or_cd,
bk.opn_dt orig_dt,
NVL(ent_summary_agen.orig_fico_score, 0) orig_fico_score,
bk.overlimit_pct overlimit_pct,
acct.ph_quality_id ph_quality_id,
NULL pmt_due_dy,
bk.prev_cyc_delq prev_cyc_delq,
NVL(bk.user_cd_1,' ') prim_cltrl_cd,
NULL prmt_cd,
bk.prod_id prod_id,
NVL (cra.prog_cd, ' ') prog_cd,
LTRIM (RTRIM (bk.rau)) rau,
NULL rcse_cd,
acct.recent_cntct_dt recent_cntct_dt,
NULL recovery_cd,
NULL rmo_xfr_officer_num,
DECODE (acct.dept_id,
801, NVL(acct.rndm_num,0),
TO_NUMBER (bk.rndm_dgt)) rndm_num,
NULL shaw_acct_cd,
NULL short_nm,
NVL (zip.st_cd, ' ') st_cd,
NULL svc_unit,
NVL (zip.tm_zone, ' ') tm_zone,
NULL vip_cd,
RPAD (bk.zip, 5) zip,
NULL nw_prmt_cd,
NULL orig_st_cd,
NVL (bk.acq_cd, ' ') acq_cd,
NULL cel_cd,
NVL(zip.rural_ak_ind, 0) rural_ak_ind,
NVL (bk.agnt_cd, ' ') agnt_cd,
NULL note_rating,
NULL most_delq_acct_ind,
NULL adv_delq_stat_cd_1,
NULL adv_delq_stat_cd_2,
NULL adv_delq_stat_cd_3,
NULL adv_delq_stat_cd_4,
NULL adv_delq_stat_cd_5,
NULL adv_delq_stat_cd_6,
NULL cntrctl_dys_past_due,
NULL cntrctl_pd_to_plus_amt,
NULL co_cd,
NULL correspond_cd,
NULL delq_cond,
NVL(ent_summary_acct.language_cd,' ') language_cd,
NULL regn_num,
NVL(bk.str_orig, 0) str_orig,
NULL str_mktg,
NULL str_svc,
NULL mrtg_num,
NULL stra_score,
NULL delq_ind,
0 coll_score,
NULL grp_cd,
NULL regn_cd,
NVL (bk.collector_cd, ' ') collector_cd,
NULL prmt_grp_id,
NULL nw_prmt_grp_id,
NULL orig_chan_cd,
NULL bnk_ctrl_rec_prod_cd,
NULL prvsnl_chrg_off_resv_amt,
NULL net_bnk_asset_val,
NULL end_of_draw_dt,
NULL disp_cd,
NULL num_of_pmts,
NVL(risk_force.recovery_score, 0) recovery_score,
DECODE (bk.chrg_off_dt, NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - bk.chrg_off_dt)
dys_snc_chrg_off,
NULL nsf_ind,
TO_NUMBER(TO_CHAR(TO_DATE('05/21/2013','mm/dd/yyyy'),'DD')) dy_of_mo,
NVL(agen.agen_id, 0) agen_id,
NVL(acct.prev_agen_id, 0) prev_agen_id,
NULL lgl_stat_cd,
CASE
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_pmt_dt
ELSE 99999
END dys_snc_lst_pmt,
NULL payoff_amt_ins,
NVL(bk.fde_hvc_cd, ' ') fde_hvc_cd,
NVL(bnkr_case.payoff_calc_ind, 0) payoff_calc_ind,
bnkr_case.pro_se_ind pro_se_ind,
-- this case statement reproduces the logic in k_bnkr.f_prejudicial.
-- calculating the prejudicial indicator this way as opposed to using the
-- function speeds up NOPS by 10 minutes(+) on the WFF critical path
CASE WHEN bnkr_case.case_id IS NULL
THEN
0
WHEN bnkr_case.dt_filed IS NULL
THEN
0
WHEN
bk.opn_dt IS NULL
THEN
0
WHEN prod_lookup.bnkr_ln_ind = 1
AND bnkr_case.dt_filed BETWEEN bk.opn_dt AND (bk.opn_dt + 90)
THEN
1
WHEN prod_lookup.bnkr_ln_ind != 1
AND bnkr_case.dt_filed BETWEEN bk.opn_dt AND (bk.opn_dt + 70)
THEN
1
ELSE
0
END prejudicial_ind,
NVL(bnkr_case.payoff_bnkr_case_pmt_srce_cd, ' ')
payoff_bnkr_case_pmt_srce_cd,
DECODE (bnkr_case.dt_filed,
NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - bnkr_case.dt_filed), 0),
99999))
dys_snc_bnkr_case_filed,
-- bnkr_court_dist_ent_id is populated subsequently
0 bnkr_court_dist_ent_id,
NVL(bnkr_case.mnl_bnkr_ind,0) mnl_bnkr_ind,
-- cmty_prop_ind is populated subsequently
0 cmty_prop_ind,
NULL invst_pool,
NULL num_of_ext,
bk.pricing_stra pricing_stra,
NULL expir_dt,
NULL yom_forced_rsn_cd,
0 coll_score_2,
0 coll_score_3,
0 coll_score_4,
0 coll_score_5,
0 coll_score_6,
NVL(risk_force.rndm_num_2,0) rndm_num_2,
NVL(risk_force.rndm_num_3,0) rndm_num_3,
NVL(risk_force.rndm_num_4,0) rndm_num_4,
NVL(risk_force.rndm_num_5,0) rndm_num_5,
NVL(risk_force.rndm_num_6,0) rndm_num_6,
NVL(risk_force.treatmnt_num,'00000000') treatmnt_num,
NULL write_dn_ind,
NULL wffbc_acct_type_cd,
NULL overlimit_amt,
NULL anl_fee_amt,
NULL wffbc_bnk_num,
NVL(risk_force.bnkr_score,0) bnkr_score,
NVL(bk.ins_ind, 0) ccrd_ins_ind,
NULL wffbc_cr_rating_cd,
NULL dys_overlimit,
DECODE (bk.lst_nsf_dt, NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_nsf_dt) dys_snc_lst_nsf_dt,
NULL dlr_at_risk,
NULL ltv_pct,
NULL num_of_accts,
NULL risk_attrition_score,
NULL risk_coll_score,
NULL test_dgt_num,
NULL wffbc_srce_cd,
NULL wffbc_queue_nm,
NULL language_id,
NVL(coll_score.risk_proba_chrg_off_score, ' ') risk_proba_chrg_off_score,
NVL(coll_score.risk_stra_1_score, ' ') risk_stra_1_score,
NVL(coll_score.risk_stra_2_score, ' ') risk_stra_2_score,
NULL dl_stra_score,
NVL(coll_score.recovery_stra_1_score,' ') recovery_stra_1_score,
NVL(coll_score.recovery_stra_2_score,' ') recovery_stra_2_score,
NULL override_prejudicial_id,
NVL(acct.addr_quality_id, 0) addr_quality_id,
NVL(acct.skip_cntct_ind, 0) skip_cntct_ind,
GREATEST(
LEAST(NVL(forcls.sale_dt,TO_DATE('05/21/2013','mm/dd/yyyy'))-
NVL(forcls.list_dt,TO_DATE('05/21/2013','mm/dd/yyyy')),9999),-9999) dys_on_mkt,
NULL portfl_cd,
DECODE(bk.dys_past_due,
NULL, 0,
bk.dys_past_due +
LAST_DAY(TO_DATE('05/21/2013','mm/dd/yyyy')) - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_past_due_eom,
NVL(recovery.recovery_stat_id, 0) recovery_stat_id,
NVL(recovery.recovery_stat_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) recovery_stat_dt,
NVL(acct.dept_id,0) dept_id,
recovery_req.recovery_req_type_id recovery_req_type_id,
recovery_req.recovery_req_rsn_id recovery_req_rsn_id,
recovery_req.dec_stat_id dec_stat_id,
recovery.hld_from_agen_until_dt hld_from_agen_until_dt,
recovery_settle.recovery_settle_stat_id recovery_settle_stat_id,
NVL(agen_tran.agen_tran_cd, ' ') agen_tran_cd,
NVL(recovery_agen_evnt_a.recovery_agen_evnt_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) recovery_agen_evnt_dt,
NULL wffrs_clnt_num,
NULL wffrs_agen_cd,
NULL wffrs_chrg_off_rsn_cd,
NULL wffrs_chrg_off_rule_id,
NULL stmt_not_sent_ind,
NVL(bk.rcse_ind,0) rcse_ind,
NULL wffrs_category_cd,
NULL wffrs_industry_cd,
TO_CHAR(NVL(bnkr_case.chapter,0)) chapter,
NULL co_borr_fico_score,
NULL cutoff_dy,
NULL wffrs_risk_stat_cd,
bnkr_case.case_id case_id,
CASE
WHEN acct.agen_asn_dt IS NOT NULL
AND bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(acct.agen_asn_dt, bk.lst_pmt_dt)
WHEN acct.agen_asn_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(acct.agen_asn_dt)
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.lst_pmt_dt)
ELSE 999999
END dys_snc_lst_pmt_snc_agen_asn,
CASE
WHEN bk.chrg_off_dt IS NOT NULL
AND bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.chrg_off_dt, bk.lst_pmt_dt)
WHEN bk.chrg_off_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.chrg_off_dt)
WHEN bk.lst_pmt_dt IS NOT NULL
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - GREATEST(bk.lst_pmt_dt)
ELSE 999999
END dys_snc_lst_pmt_snc_chrg_off,
NULL led_bnk_ind,
NULL dys_snc_cutoff_dy,
NULL wffrs_sys_cd,
NULL wffrs_dlr_id,
NULL wffrs_delq_stat_cd,
recovery_settle.settle_amt settle_amt,
DECODE (recovery_agen_evnt_a.recovery_agen_evnt_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - recovery_agen_evnt_a.recovery_agen_evnt_dt)
dys_snc_agen_evnt,
DECODE (recovery.recovery_stat_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - recovery.recovery_stat_dt)
dys_snc_recovery_stat_chg,
NULL overlimit_scenario_score,
NULL wffrs_ins_cd,
NULL opn_dt,
bk.cacs_user_routing cacs_user_routing,
bk.bal payoff_amt_bal,
NVL(dstr_desc_lkup.dstr_type_id,0) dstr_type_id,
NVL(dstr.dstr_desc_id,0) dstr_desc_id,
NVL(dstr_impact_lvl_lkup.dstr_impact_lvl_val,0) dstr_impact_lvl_id,
NULL reaff_risk_stat_cd,
NULL wffrs_clsd_stat_cd_prim,
NULL wffrs_clsd_stat_cd_scndry,
NULL shaw_acct_cat_cd,
NULL acct_in_feed_ind,
NVL(acct.chrg_off_type_id,0) chrg_off_type_id, -- default to full if charged off
bnkr_case.bnkr_mtch_cd bnkr_mtch_cd,
bnkr_case.agen_ntc_type_cd agen_ntc_type_cd,
NULL dys_until_cutoff_dy,
NULL fis_delq_cl_cd,
NULL fis_mn_cd,
NULL fis_org_cd,
NULL fis_anal_stop_cd,
NULL fis_bad_chk_stop_cd,
NULL fis_disb_stop_cd,
NULL fis_forcls_stop_cd,
NULL fis_no_ntc_stop_cd,
NULL fis_pd_in_full_stop_cd,
NULL fis_proc_stop_cd,
NULL tot_amt_due,
NVL(real_estate.real_estate_prop_type_cd, ' ')
real_estate_prop_type_cd,
NVL(forcls.forcls_stat_id, 0) forcls_stat_id,
NULL dys_until_no_ntc_stop_expir_dt,
NULL dys_until_proc_stop_expir_dt,
DECODE
(coll_act.dir_asst_cntct_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.dir_asst_cntct_dt) dys_snc_dir_asst_cntct_dt,
DECODE
(coll_act.cust_info_dda_ver_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.cust_info_dda_ver_dt)
dys_snc_cust_info_dda_ver_dt,
DECODE
(coll_act.vend_srch_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.vend_srch_dt) dys_snc_vend_srch_dt,
DECODE
(coll_act.empnt_ver_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.empnt_ver_dt) dys_snc_empnt_ver_dt,
DECODE
(coll_act.other_acct_rvw_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.other_acct_rvw_dt) dys_snc_other_acct_rvw_dt,
0 dys_past_cccs_pmt_due_dt,
DECODE
(coll_act.arch_srch_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - coll_act.arch_srch_dt) dys_snc_arch_srch_dt,
DECODE (forcls.sr_sale_bid_dt,
NULL, 99999,
forcls.sr_sale_bid_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_sr_sale_bid_dt,
DECODE (forcls.sr_sale_dt,
NULL, 99999,
forcls.sr_sale_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_sr_sale_dt,
NVL(forcls.third_party_sale_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) third_party_sale_dt,
NVL(forcls.forcls_resume_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) forcls_resume_dt,
NVL(forcls.sr_sale_bid_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) sr_sale_bid_dt,
NVL(forcls.sr_sale_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) sr_sale_dt,
DECODE
(forcls.third_party_sale_dt,
NULL, 99999,
forcls.third_party_sale_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_third_party_sale_dt,
DECODE
(forcls.forcls_resume_dt,
NULL, 99999,
forcls.forcls_resume_dt - TO_DATE('05/21/2013','mm/dd/yyyy')) dys_until_forcls_resume_dt,
0 coll_scenario_score,
' ' fis_bnkr_workstn_stat_cd,
' ' fis_forcls_workstn_stat_cd,
' ' loss_mitigat_workstn_stat_cd,
' ' fis_invst_type_cd,
' ' fis_sscra_cd,
NVL(acct_pre_queue_atr.call_center_agen_asn_ind,0)
call_center_agen_asn_ind,
NVL2(acct_pre_queue_atr.call_center_agen_unasn_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.call_center_agen_unasn_dt, 0)
dys_snc_call_center_agen_unasn,
NVL2(acct_pre_queue_atr.max_call_center_agen_asn_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.max_call_center_agen_asn_dt, 0)
dys_snc_call_center_agen_asn,
NVL(coll_score.risk_pricing_updt_dt,
TO_DATE('01/01/1900','MM/DD/YYYY')) risk_pricing_updt_dt,
NVL(coll_score.srm_behavior_score,' ') srm_behavior_score,
NVL(coll_score.risk_pricing_cd,' ') risk_pricing_cd,
NVL(coll_score.risk_pricing_curr_int_rt,0) risk_pricing_curr_int_rt,
NVL(coll_score.risk_pricing_orig_int_rt, 0) risk_pricing_orig_int_rt,
NVL(coll_score.risk_pricing_orig_cr_lmt_amt, 0) risk_pricing_orig_cr_lmt_amt,
NVL(coll_score.risk_pricing_curr_cr_lmt_amt, 0) risk_pricing_curr_cr_lmt_amt,
NVL(coll_score.risk_pricing_hi_risk_flg_score, ' ') risk_pricing_hi_risk_flg_score,
NVL(coll_score.risk_pricing_strght_rolr_score, ' ') risk_pricing_strght_rolr_score,
NVL(coll_score.risk_pricing_frbr_score, ' ') risk_pricing_frbr_score,
NVL(coll_score.risk_pricing_lgl_score, ' ') risk_pricing_lgl_score,
NVL(forcls.attorney_refd_dt, TO_DATE('01/01/1900', 'mm/dd/yyyy'))
attorney_refd_dt,
NVL(bk.csh_int_rt,0) csh_int_rt,
NVL(bk.chrg_off_amt,0) chrg_off_amt,
NVL(bk.closure_dt, TO_DATE('01/01/1900', 'mm/dd/yyyy'))
closure_dt,
NVL(bk.int_rate,0) int_rate,
NVL(bk.merchandise_int_rt,0) merchandise_int_rt,
NVL(bk.overlimit_amt,0) fde_overlimit_amt,
CASE WHEN acct.dept_id = 801
THEN
CASE WHEN bk.bk_stat_cd = 'Z'
THEN
NVL(bk.amt_past_due, 0)
ELSE
NVL(bk.tot_amt_due, 0)
END
ELSE
NVL(bk.tot_amt_due, 0)
END fde_tot_amt_due,
NVL(risk_force.coll_score_cd_1,0) coll_score_cd_1,
NVL(risk_force.coll_score_cd_2,0) coll_score_cd_2,
NVL(risk_force.coll_score_cd_3,0) coll_score_cd_3,
NVL(risk_force.coll_score_cd_4,0) coll_score_cd_4,
NVL(risk_force.coll_score_cd_5,0) coll_score_cd_5,
NVL(risk_force.coll_score_cd_6,0) coll_score_cd_6,
NVL(risk_force.rndm_num_1,0) rndm_num_1,
0 recover_corp_adv_bal_amt,
0 nsf_fee_amt,
0 lte_fee_amt,
0 other_fee_amt,
0 susp_bal_amt,
NVL(coll_score.call_score, 0) call_score,
NVL(coll_score.hld_out_stra_cd, ' ') hld_out_stra_cd,
NVL(coll_score.no_call_score, 0) no_call_score,
NVL(coll_score.strght_rolr_stra_cd, ' ') strght_rolr_stra_cd,
NVL(coll_score.triad_rndm_num, ' ') triad_rndm_num,
NVL(coll_score.triad_scenario_score, ' ') triad_scenario_score,
NVL(coll_score.triad_stra_score, ' ') triad_stra_score,
NVL(coll_score.triad_treatmnt_num, ' ') triad_treatmnt_num,
0 elig_for_ext_reage,
0 dys_snc_arm_frst_pmt_dt,
0 dys_until_arm_frst_pmt_dt,
0 adj_rt_mrtg_ind,
0 dys_snc_int_rt_strt_dt,
0 dys_snc_int_rt_end_dt,
0 int_rt,
0 pmt_amt,
0 dys_snc_prev_int_rt_strt_dt,
0 dys_snc_prev_int_rt_end_dt,
0 prev_int_rt,
0 prev_pmt_amt,
0 dys_until_next_int_rt_chg_dt,
0 dys_until_next_pmt_chg_dt,
0 next_int_rt,
0 next_pmt_amt,
0 dys_until_nxt_reset_dt,
0 dys_until_frst_reset_dt,
0 num_of_pmts_past_due,
0 mo_past_due_num,
' ' fis_prior_svcr_cd,
0 benft_req_stat_id,
0 benft_req_type_id,
' ' shaw_ins_prod_cd_prot_plan,
' ' shaw_ins_stat_cd_prot_plan,
NVL2(spcl_hdlg.dt,
TO_DATE('05/21/2013','mm/dd/yyyy') - trunc(spcl_hdlg.dt), 0) dys_snc_cccs_pps_accpt,
NVL(bk.stat_lst_chg_rsn_cd,0) stat_lst_chg_rsn_cd,
NVL(ent_summary_agen.curr_fico_score,0) bur_score,
NVL(bk.cacs_rsn_cd,' ') cacs_rsn_cd,
NVL(bk.fix_pmt_amt,0) fix_pmt_amt,
NVL(bk.prom_to_pay_ind,0) prom_to_pay_ind,
NVL(bk.mtch_pay_prog_ind,0) mtch_pay_prog_ind,
NVL(bk.react_prog_ind,0) react_prog_ind,
NVL(bk.pre_bnkr_ind,'0') pre_bnkr_ind,
NVL(risk_force.fdebc_risk_stat_cd,'0') risk_stat_cd,
NVL(risk_force.adaptation_score,0) adaptation_score,
NVL(risk_force.ermc_score,' ') ermc_score,
NVL(risk_force.attrition_score,0) attrition_score,
NVL(bk.prev_bk_stat_cd,' ') prev_bk_stat_cd,
NVL(bk.corp_nm,' ') corp_nm,
NVL(bk.clnt_num,' ') clnt_num,
DECODE(bk.bill_cyc, NULL, 0,
TO_NUMBER(TO_CHAR(TO_DATE('05/21/2013','mm/dd/yyyy') - bk.bill_cyc,'DD')))
dys_snc_bill_cyc,
NVL(bk.coll_cd,0) fde_coll_cd,
NVL(bk.lst_stmt_dt,to_date('01/01/1900', 'mm/dd/yyyy'))
lst_stmt_dt,
' ' alpha_type,
0 defr_int_bal,
0 tot_defr_int_bal,
NVL(risk_force.fut_treatmnt_int_rt,0) fut_treatmnt_int_rt,
NVL(risk_force.fut_treatmnt_pmt_amt,0) fut_treatmnt_pmt_amt,
LEAST(GREATEST(DECODE
(acct.last_right_cntct_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct.last_right_cntct_dt),0),99999) dys_snc_right_party_cntct,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_frst_pmt_dt,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_shaw_rschd_dt,
0 cccs_pps_act_ind,
' ' cccs_pps_stat_desc,
' ' cccs_pps_agen_nm,
' ' cccs_pps_agen_cd,
0 cccs_pps_nxt_pmt_no,
to_date('01/01/1900', 'mm/dd/yyyy') cccs_pps_nxt_pmt_dt,
NVL(acct.buyer_ent_id, 0) buyer_ent_id,
NVL(acct.cell_ph_consent_no_ind,0) cell_ph_consent_no_ind,
NVL(acct.cell_ph_consent_unknown_ind,0) cell_ph_consent_unknown_ind,
NVL(acct.cell_ph_consent_yes_ind,0) cell_ph_consent_yes_ind,
NVL(rstrc.rstrc_stat_id, 0) rstrc_stat_id,
NVL(bnkr_case.due_amt_pst_arrears_trustee,0) due_amt_pst_arrears_trustee,
NVL(bnkr_case.due_amt_pst_arrears_direct,0) due_amt_pst_arrears_direct,
NVL(bnkr_case.due_amt_pre_arrears_direct,0) due_amt_pre_arrears_direct,
NVL(bnkr_case.due_amt_pre_arrears_trustee,0) due_amt_pre_arrears_trustee,
NVL(bnkr_case.due_amt_secured_direct,0) due_amt_secured_direct,
NVL(bnkr_case.due_amt_secured_trustee,0) due_amt_secured_trustee,
NVL(bnkr_case.due_amt_unsecured_direct,0) due_amt_unsecured_direct,
NVL(bnkr_case.due_amt_unsecured_trustee,0) due_amt_unsecured_trustee,
NVL(bnkr_case.bal_amt_pst_arrears_direct,0) bal_amt_pst_arrears_direct,
NVL(bnkr_case.bal_amt_pst_arrears_trustee,0) bal_amt_pst_arrears_trustee,
NVL(bnkr_case.bal_amt_pre_arrears_direct,0) bal_amt_pre_arrears_direct,
NVL(bnkr_case.bal_amt_pre_arrears_trustee,0) bal_amt_pre_arrears_trustee,
NVL(bnkr_case.bal_amt_secured_direct,0) bal_amt_secured_direct,
NVL(bnkr_case.bal_amt_secured_trustee,0) bal_amt_secured_trustee,
NVL(bnkr_case.bal_amt_unsecured_direct,0) bal_amt_unsecured_direct,
NVL(bnkr_case.bal_amt_unsecured_trustee,0) bal_amt_unsecured_trustee,
NVL(bnkr_case.plan_amt_pst_arrears_direct,0) plan_amt_pst_arrears_direct,
NVL(bnkr_case.plan_amt_pst_arrears_trustee,0) plan_amt_pst_arrears_trustee,
NVL(bnkr_case.plan_amt_pre_arrears_direct,0) plan_amt_pre_arrears_direct,
NVL(bnkr_case.plan_amt_pre_arrears_trustee,0) plan_amt_pre_arrears_trustee,
NVL(bnkr_case.plan_amt_secured_direct,0) plan_amt_secured_direct,
NVL(bnkr_case.plan_amt_secured_trustee,0) plan_amt_secured_trustee,
NVL(bnkr_case.plan_amt_unsecured_direct,0) plan_amt_unsecured_direct,
NVL(bnkr_case.plan_amt_unsecured_trustee,0) plan_amt_unsecured_trustee,
LEAST(GREATEST(DECODE(bnkr_case.pst_petition_pd_to_dt_direct,
NULL,99999,
SYSDATE - bnkr_case.pst_petition_pd_to_dt_direct),0),99999)
dys_snc_pst_peti_pd_to_dt_dir,
LEAST(GREATEST(DECODE(bnkr_case.pst_petition_pd_to_dt_trustee,
NULL,99999,
SYSDATE - bnkr_case.pst_petition_pd_to_dt_trustee),0),99999)
dys_snc_pst_peti_pd_to_dt_trus,
NVL(bnkr_case.prin_bal_pst_arrears_direct,0) prin_bal_pst_arrears_direct,
NVL(bnkr_case.prin_bal_pst_arrears_trustee,0) prin_bal_pst_arrears_trustee,
NVL(bnkr_case.prin_bal_pre_arrears_direct,0) prin_bal_pre_arrears_direct,
NVL(bnkr_case.prin_bal_pre_arrears_trustee,0) prin_bal_pre_arrears_trustee,
NVL(bnkr_case.prin_bal_secured_direct,0) prin_bal_secured_direct,
NVL(bnkr_case.prin_bal_secured_trustee,0) prin_bal_secured_trustee,
NVL(bnkr_case.prin_bal_unsecured_direct,0) prin_bal_unsecured_direct,
NVL(bnkr_case.prin_bal_unsecured_trustee,0) prin_bal_unsecured_trustee,
NVL(real_estate.real_estate_mkt_cond_id,0) real_estate_mkt_cond_id,
0 ext_reage_dec_id,
0 dys_snc_dsn_dt,
0 ext_reage_dec_rsn_id,
0 ext_reage_stat_id,
NVL(ext_reage_2.mitigat_plan_type_id,0) mitigat_plan_type_id,
0 dys_snc_new_matur_dt,
0 hld_cd,
0 hm_price_idx_val,
0 fmly_payoff_amt_prin,
0 fmly_net_bnk_asset_val,
0 fmly_payoff_amt_int,
0 fmly_curr_pmt,
0 fmly_tot_amt_due,
99999 fmly_borr_next_due_in_dys,
0 fmly_dly_weigh_avg_int_rt,
LEAST(GREATEST(DECODE(dstr.dstr_dt,
NULL,99999,
SYSDATE - dstr.dstr_dt),0),99999) dys_snc_dstr_dt,
LEAST(GREATEST(DECODE(dstr.relief_prd_expir_dt,
NULL,99999,
SYSDATE - dstr.relief_prd_expir_dt),0),99999)
dys_snc_relief_prd_expir_dt,
NVL(bk.mrchnt_num,' ') mrchnt_num,
NVL(bk.fde_industry_cd,' ') industry_cd,
NVL(bk.sys_cd,' ') sys_cd,
NVL(risk_force.risk_atr_1,'0') risk_atr_1,
NVL(risk_force.risk_atr_2,'0') risk_atr_2,
NVL(risk_force.risk_atr_3,'0') risk_atr_3,
NVL(risk_force.risk_atr_4,'0') risk_atr_4,
NVL(risk_force.risk_atr_5,'0') risk_atr_5,
NVL(risk_force.risk_atr_6,'0') risk_atr_6,
NVL(risk_force.risk_atr_7,'0') risk_atr_7,
NVL(risk_force.risk_atr_8,'0') risk_atr_8,
NVL(risk_force.risk_atr_9,'0') risk_atr_9,
NVL(risk_force.risk_atr_10,'0') risk_atr_10,
NVL(risk_force.msa_cd,'0') msa_cd,
NVL(risk_force.cbsa_cd,'0') cbsa_cd,
NVL(risk_force.ud_1_cd,0) ud_1_cd,
NVL(risk_force.ud_2_cd,0) ud_2_cd,
NVL(risk_force.ud_3_cd,0) ud_3_cd,
NVL(risk_force.ud_4_cd,0) ud_4_cd,
NVL(bk.prin_cd,' ') prin_cd,
0 curr_due_amt,
0 avm_hm_appr_val,
' ' cr_line_mgmt_cd,
0 user_def_coll_stra_proba_pct_1,
0 user_def_coll_stra_proba_pct_2,
0 user_def_coll_stra_proba_pct_3,
0 user_def_coll_stra_proba_pct_4,
0 user_def_coll_stra_proba_pct_5,
0 user_def_coll_stra_score_1,
0 user_def_coll_stra_score_2,
0 user_def_coll_stra_score_3,
0 user_def_coll_stra_score_4,
0 user_def_coll_stra_score_5,
0 user_def_coll_stra_amt_1,
0 user_def_coll_stra_amt_2,
0 user_def_coll_stra_amt_3,
' ' user_def_coll_stra_cd_1,
' ' user_def_coll_stra_cd_2,
' ' user_def_coll_stra_cd_3,
' ' user_def_coll_stra_cd_4,
' ' user_def_coll_stra_cd_5,
' ' user_def_coll_stra_cd_6,
' ' user_def_coll_stra_cd_7,
TO_DATE('01/01/1900', 'mm/dd/yyyy') chrg_off_dec_stat_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') equity_anal_compl_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') sr_ver_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') tax_chk_dt,
TO_DATE('01/01/1900', 'mm/dd/yyyy') tax_due_dt,
0 delq_tax,
0 tax_pd_thru_escrow_ind,
TO_DATE('01/01/1900', 'MM/DD/YYYY') mcod_dt,
0 mcod_stream_id,
' ' pool_ins_cd,
' ' pool_ins_claim_stat_cd,
0 dys_snc_full_chrg_off_dt,
NVL(ent_summary_acct.curr_fico_score,' ') risk_curr_fico_score,
NVL(ent_summary_acct.orig_fico_score,' ') risk_orig_fico_score,
NVL(bk.acct_typ_cd,' ') acct_typ_cd,
' ' sch_cd,
' ' prod_desc,
' ' prod_cd,
' ' city,
' ' ph_num,
TO_DATE('01/01/1900', 'MM/DD/YYYY') def_forb_end_dt,
' ' defer_grp_cd,
0 cosign_present_ind,
' ' frst_pmt_dflt_cd,
TO_DATE('01/01/1900', 'MM/DD/YYYY') curr_pmt_due_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') orig_contract_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') disb_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') left_school_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY') grad_dt,
0 grace_period_dys,
TO_DATE('01/01/1900', 'MM/DD/YYYY') separation_dt,
' ' earn_learn_stat_cd,
0 fraud_ind,
0 cease_desist_ind,
0 deceased_ind,
TO_DATE('01/01/1900', 'MM/DD/YYYY') judg_dt,
' ' lgl_st_cd,
0 ln_dischrg_ind,
' ' acct_srce_cd,
' ' recovery_collector_cd,
' ' prod_typ_cd,
' ' bnk_cd,
NVL (real_estate.prop_cond_id, 0) prop_cond_id,
NVL (real_estate.prop_occ_stat_id, 0) prop_occ_stat_id,
NVL (acct.hamp_fallout_rsn_id, 0) hamp_fallout_rsn_id,
acct.hamp_fallout_rsn_dt hamp_fallout_rsn_dt,
NVL2(acct.hamp_fallout_rsn_dt, TO_DATE('05/21/2013','mm/dd/yyyy')
- acct.hamp_fallout_rsn_dt, 0) dys_snc_hamp_fallout_rsn_dt,
NVL(bk.user_pricing_cd,' ') user_pricing_cd,
NVL(bk.fde_srce_cd,' ') fde_srce_cd,
0 treatmnt_num_1,
0 treatmnt_num_2,
0 treatmnt_num_3,
0 treatmnt_num_4,
0 treatmnt_num_5,
0 treatmnt_num_6,
TO_DATE('01/01/1900','mm/dd/yyyy') sr_expir_dt,
0 outstdg_bal_ind,
0 outstdg_bal_amt ,
NULL non_rcvd_order_dt,
TO_DATE('05/21/2013','mm/dd/yyyy') todays_dt,
0 max_appr_val,
NULL ignr_prev_bpo_notneedavail_ind,
NULL ignr_prev_intr_bpo_ind,
NULL intr_bpo_exists_ind,
NULL bpo_notneedavail_exists_ind,
NULL coll_addr_1,
NULL coll_city,
NULL coll_st_cd,
NULL coll_zip,
NULL coll_apn_num,
NULL cncl_fut_bpo_cd,
NULL east_ind,
' ' efs_correspond_cd,
0 pst_petition_debt_ind,
TO_DATE('01/01/1900','mm/dd/yyyy') lgl_stip_dt,
NVL(acct_pre_queue_atr.pre_lqdtn_bal, 0) pre_lqdtn_bal,
NVL(acct_pre_queue_atr.lqdtn_amt_pstd, 0) lqdtn_amt_pstd,
NVL(acct_pre_queue_atr.debt_outstdg_amt, 0) debt_outstdg_amt,
0 bnkr_ind,
0 recon_dec_ind,
TO_DATE('01/01/1900','mm/dd/yyyy') recon_dec_dt,
0 dlgt_auth_lvl,
TO_DATE('01/01/1900','mm/dd/yyyy') recon_compl_dt,
NVL(
(CASE
WHEN bk.chrg_off_dt IS NOT NULL
THEN
CASE WHEN bk.lst_pmt_dt IS NOT NULL
AND bk.lst_pmt_dt > bk.chrg_off_dt
THEN TO_DATE('05/21/2013','mm/dd/yyyy') - bk.lst_pmt_dt
END
END),0) dys_snc_pst_chrg_off_pmt,
NVL(bk.non_acrl_cd,' ') non_acrl_cd,
' ' afs_rsn_stat_cd,
NVL(ent_summary_acct.cr_rpt_fico_score,0) cr_rpt_fico_score_borr,
NVL(ent_summary_acct.cr_rpt_dt,
TO_DATE('01/01/1900','mm/dd/yyyy')) cr_rpt_dt_borr,
' ' str_orig_st_cd,
0 cr_rpt_fico_score_co_borr,
TO_DATE('01/01/1900','mm/dd/yyyy') cr_rpt_dt_co_borr,
0 po_box_ind_borr,
0 po_box_ind_co_borr,
0 frbr_ind,
NVL(bk.sic_fde_industry_id,0) sic_fde_industry_id,
NVL(bk.sic_industry_id,0) sic_industry_id,
0 cell_ph_rating_unknown_ind,
NVL(acct.cell_ph_ver_consent_yes_ind_1,0) cell_ph_ver_consent_yes_ind_1,
NVL(acct.cell_ph_ver_consent_yes_ind_2,0) cell_ph_ver_consent_yes_ind_2,
NVL(acct.spoc_asn_stat_id,0) spoc_asn_stat_id,
NVL(acct.spoc_asn_rsn_id,0) spoc_asn_rsn_id,
DECODE(spoc_asn_stat.spoc_act_ind,
NULL,0,
spoc_asn_stat.spoc_act_ind) spoc_act_ind,
NVL(acct.spoc_login_cd,' ') spoc_login_cd,
NULL dys_snc_rvw_dt,
NVL(bk.fde_acct_language_cd,' ') fde_acct_language_cd,
0 scra_elig_ind,
NVL(bk.fdebc_nowline_lien_stat_cd, ' ') fdebc_nowline_lien_stat_cd,
DECODE(bk.reage_dt,
NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - bk.reage_dt), 0), 99999))
dys_snc_lst_reage_dt,
NVL(bk.tot_reage_hist, 0) tot_reage_hist,
DECODE
(acct_mil_svc.act_duty_start_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.act_duty_start_dt))
dys_snc_act_duty_start_dt,
DECODE
(acct_mil_svc.act_duty_end_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.act_duty_end_dt))
dys_snc_act_duty_end_dt,
DECODE
(acct_mil_svc.order_rcv_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(acct_mil_svc.order_rcv_dt))
dys_snc_order_rcv_dt,
NVL(forcls.forcls_outsource_dt,
TO_DATE('01/01/1900', 'MM/DD/YYYY')) forcls_outsource_dt,
DECODE (acct.cntct_stra_email_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_email_dt), 0), 99999))
dys_snc_cntct_stra_email_dt,
DECODE (acct.cntct_stra_txt_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_txt_dt), 0), 99999))
dys_snc_cntct_stra_txt_dt,
DECODE (acct.cntct_stra_imd_pre_auth_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_imd_pre_auth_dt), 0), 99999))
dys_snc_cntct_stra_pre_auth_dt,
DECODE (acct.cntct_stra_imd_pre_impt_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_imd_pre_impt_dt), 0), 99999))
dys_snc_cntct_stra_pre_impt_dt,
DECODE (acct.cntct_stra_misc_1_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_1_dt), 0), 99999))
dys_snc_cntct_stra_misc_1_dt,
DECODE (acct.cntct_stra_misc_2_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_2_dt), 0), 99999))
dys_snc_cntct_stra_misc_2_dt,
DECODE (acct.cntct_stra_misc_3_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_3_dt), 0), 99999))
dys_snc_cntct_stra_misc_3_dt,
DECODE (acct.cntct_stra_misc_4_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_misc_4_dt), 0), 99999))
dys_snc_cntct_stra_misc_4_dt,
DECODE (acct.cntct_stra_sor_ltr_dt, NULL, 99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - acct.cntct_stra_sor_ltr_dt), 0), 99999))
dys_snc_cntct_stra_sor_ltr_dt,
NULL mrtg_portfl_cd,
NULL fis_acct_num,
NULL msp_clnt_num,
settle.settle_stat_id settle_stat_id,
DECODE (settle.next_settle_pmt_due_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(settle.next_settle_pmt_due_dt))
dys_snc_next_settle_pmt_due,
DECODE (lgl_pre_asn.lgl_dec_dt,
NULL,
99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - TRUNC(lgl_pre_asn.lgl_dec_dt)), 0), 99999))
dys_snc_lgl_dec_dt,
NVL(chrg_off_dec.chrg_off_dec_stat_id,0) chrg_off_dec_stat_id,
real_estate.vesting vesting,
DECODE (real_estate.deed_of_trust_chk_dt,
NULL,
99999,
LEAST (GREATEST ((TO_DATE('05/21/2013','mm/dd/yyyy') - real_estate.deed_of_trust_chk_dt), 0), 99999))
dys_snc_deed_of_trust_chk_dt,
real_estate.county_rec county_rec,
' ' spcl_alloc_ind_num,
NVL(acct.cell_ph_consent_not_yes_ind,0) cell_ph_consent_not_yes_ind,
0 cell_ph_consent_not_no_ind,
DECODE(acct_ent_acct.cntct_type_id, 1, NVL(ent_summary_acct.liable_ind, 0), 0) borr_liable_ind,
0 co_signer_1_liable_ind,
0 co_signer_2_liable_ind,
0 co_signer_3_liable_ind,
0 student_liable_ind,
' ' co_signer_1_state,
' ' co_signer_2_state,
' ' co_signer_3_state,
' ' student_state,
' ' co_signer_1_efs_correspond_cd,
' ' co_signer_2_efs_correspond_cd,
' ' co_signer_3_efs_correspond_cd,
' ' student_efs_correspond_cd,
' ' eodrw_proc_cd,
' ' eodrw_ltr_90_cd,
' ' eodrw_ltr_60_cd,
' ' eodrw_ltr_30_cd,
' ' eodrw_ltr_final_cd,
' ' mat_ltr_90_cd,
' ' mat_ltr_60_cd,
' ' mat_ltr_30_cd,
' ' real_estate_prop_type_cd_orig,
' ' cltrl_st_cd,
risk_force.mis_atr_num_1 mis_atr_num_1,
risk_force.mis_atr_num_2 mis_atr_num_2,
risk_force.mis_atr_num_3 mis_atr_num_3,
risk_force.mis_atr_num_4 mis_atr_num_4,
risk_force.mis_atr_num_5 mis_atr_num_5,
risk_force.mis_atr_num_6 mis_atr_num_6,
risk_force.mis_atr_num_7 mis_atr_num_7,
risk_force.mis_atr_num_8 mis_atr_num_8,
risk_force.mis_atr_num_9 mis_atr_num_9,
risk_force.mis_atr_num_10 mis_atr_num_10,
risk_force.mis_atr_num_11 mis_atr_num_11,
risk_force.mis_atr_num_12 mis_atr_num_12,
risk_force.mis_atr_num_13 mis_atr_num_13,
risk_force.mis_atr_num_14 mis_atr_num_14,
risk_force.mis_atr_num_15 mis_atr_num_15,
risk_force.mis_atr_num_16 mis_atr_num_16,
risk_force.mis_atr_num_17 mis_atr_num_17,
risk_force.mis_atr_num_18 mis_atr_num_18,
risk_force.mis_atr_num_19 mis_atr_num_19,
risk_force.mis_atr_num_20 mis_atr_num_20,
risk_force.mis_atr_num_21 mis_atr_num_21,
risk_force.mis_atr_num_22 mis_atr_num_22,
risk_force.mis_atr_num_23 mis_atr_num_23,
risk_force.mis_atr_num_24 mis_atr_num_24,
risk_force.mis_atr_num_25 mis_atr_num_25,
risk_force.mis_atr_num_26 mis_atr_num_26,
risk_force.mis_atr_num_27 mis_atr_num_27,
risk_force.mis_atr_num_28 mis_atr_num_28,
risk_force.mis_atr_num_29 mis_atr_num_29,
risk_force.mis_atr_num_30 mis_atr_num_30,
risk_force.mis_atr_num_31 mis_atr_num_31,
risk_force.mis_atr_num_32 mis_atr_num_32,
risk_force.mis_atr_num_33 mis_atr_num_33,
risk_force.mis_atr_num_34 mis_atr_num_34,
risk_force.mis_atr_num_35 mis_atr_num_35,
risk_force.mis_atr_num_36 mis_atr_num_36,
risk_force.mis_atr_num_37 mis_atr_num_37,
risk_force.mis_atr_num_38 mis_atr_num_38,
risk_force.mis_atr_num_39 mis_atr_num_39,
risk_force.mis_atr_num_40 mis_atr_num_40,
risk_force.mis_atr_num_41 mis_atr_num_41,
risk_force.mis_atr_dt_1 mis_atr_dt_1,
risk_force.mis_atr_dt_2 mis_atr_dt_2,
risk_force.mis_atr_dt_3 mis_atr_dt_3,
risk_force.mis_atr_txt_1 mis_atr_txt_1,
risk_force.mis_atr_txt_2 mis_atr_txt_2,
risk_force.mis_atr_txt_3 mis_atr_txt_3,
risk_force.mis_atr_amt_1 mis_atr_amt_1,
risk_force.mis_atr_amt_2 mis_atr_amt_2,
risk_force.mis_atr_amt_3 mis_atr_amt_3,
NVL(bk.auth_flg_cd,' ') auth_flg_cd,
NVL(acct.no_dl_permission,0) no_dl_permission,
NVL(bk.internal_stat_cd,' ') internal_stat_cd,
SUBSTR(bk.bk_acct_num,-2,2) lst_2_dgt_acct_num,
SUBSTR(bk.misc_fld_7,7,1) misc_fld_7_pos_7,
SUBSTR(bk.bk_acct_num,-1,1) lst_dgt_acct_num,
NVL(bk.stmt_hld_cd,' ') stmt_hld_cd,
NVL(bk.cr_bur_cd,' ') cr_bur_rpt_cd,
bk.delq_amt_cyc5 delq_amt_cyc5,
bk.delq_amt_cyc6 delq_amt_cyc6,
bk.delq_amt_cyc7 delq_amt_cyc7,
NULL dys_past_due_360,
0 lst_3_dgt_acct_num,
' ' lst_tran_cd,
0 dys_lst_mont_tran,
0 cltrl_cnt,
NVL(acct_pre_queue_atr.chk_by_ph_pmt_delq_cyc_5_ind, 0) chk_by_ph_pmt_delq_cyc_5_ind,
NVL(acct_pre_queue_atr.vca_prom_amt_delq_cyc_5_ind, 0) vca_prom_amt_delq_cyc_5_ind,
NVL(acct_pre_queue_atr.chk_by_ph_pmt_delq_cyc_7_ind, 0) chk_by_ph_pmt_delq_cyc_7_ind,
NVL(acct_pre_queue_atr.vca_prom_amt_delq_cyc_7_ind, 0) vca_prom_amt_delq_cyc_7_ind,
DECODE (acct_pre_queue_atr.dys_snc_lst_ma_cntct_ltr_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.dys_snc_lst_ma_cntct_ltr_dt)
dys_snc_lst_ma_cntct_ltr_dt,
DECODE (acct.rtc_ltr_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct.rtc_ltr_dt ) dys_snc_lst_cure_dt,
acct_pre_queue_atr.lst_cure_ltr_st_cd lst_cure_ltr_st_cd,
acct_pre_queue_atr.cnt_cure_ltr_snc_lst_365_dys cnt_cure_ltr_snc_lst_365_dys,
SUBSTR(bk.misc_fld_7,4,1) misc_fld_7_pos_4,
SUBSTR(bk.misc_fld_7,1,1) misc_fld_7_pos_1,
bk.ins_ind ins_ind,
bk.life_ins_prod_cd life_ins_prod_cd,
bk.chrg_off_exc_cd chrg_off_exc_cd,
bk.spcl_flg_5_cd spcl_flg_5_cd,
bk.spcl_flg_6_cd spcl_flg_6_cd,
bk.spcl_flg_8_cd spcl_flg_8_cd,
DECODE (acct_pre_queue_atr.dys_snc_right_time_pmt_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.dys_snc_right_time_pmt_dt )
dys_snc_right_time_pmt_dt,
DECODE (acct_pre_queue_atr.settle_expir_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.settle_expir_dt)
settle_expir_dt,
DECODE (acct_pre_queue_atr.judg_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.judg_dt)
dys_snc_judg_dt,
DECODE (acct_pre_queue_atr.renewal_dt,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.renewal_dt)
renewal_dt,
DECODE (acct_pre_queue_atr.orig_judg_exp_dt,
NULL, 99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.orig_judg_exp_dt)
orig_judg_exp_dt,
DECODE (acct_pre_queue_atr.renewal_final_exp_dt ,
NULL,
99999,
TO_DATE('05/21/2013','mm/dd/yyyy') - acct_pre_queue_atr.renewal_final_exp_dt)
renewal_final_exp_dt
FROM t_acct_fde_nops_queue acct,
t_bnkr_case bnkr_case,
t_bk bk,
t_acct_ent acct_ent_acct,
t_acct_ent acct_ent_agen,
t_agen_ent agen,
t_cra_lookup cra,
t_zip_lookup zip,
t_agen_tran agen_tran,
t_recovery recovery,
t_recovery_req recovery_req,
t_recovery_agen_evnt recovery_agen_evnt_a,
(SELECT *
FROM t_recovery_settle
WHERE (acct_id, recovery_settle_id) IN
(SELECT acct_id, MAX(recovery_settle_id) recovery_settle_id
FROM t_recovery_settle
GROUP BY acct_id)) recovery_settle,
(SELECT acct_id,
MAX(reco_agen_evnt.agen_tran_id) agen_tran_id
FROM t_recovery_agen reco_agen,
t_recovery_agen_evnt reco_agen_evnt
WHERE reco_agen.recovery_agen_id = reco_agen_evnt.recovery_agen_id
GROUP BY reco_agen.acct_id) recovery_agen_evnt_b,
t_acct_cltrl acct_cltrl,
t_forcls forcls,
t_prod_lookup prod_lookup,
t_real_estate real_estate,
t_acct_coll_act coll_act,
t_acct_pre_queue_atr PARTITION(NOPS) acct_pre_queue_atr,
t_risk_force risk_force,
t_ent_summary ent_summary_acct,
t_ent_summary ent_summary_agen,
t_ln_spcl_hdlg_stat spcl_hdlg,
t_dstr_desc_lookup dstr_desc_lkup,
t_dstr_impact_lvl_lookup dstr_impact_lvl_lkup,
(select * from t_dstr where prim_ind = 1) dstr,
t_rstrc rstrc,
t_rstrc_acct rstrc_acct,
t_coll_stra_score coll_score,
(select rank () over (partition by acct_id
order by req_dt, ext_reage_id desc nulls last) rank,
ext_reage.acct_id acct_id,
ext_reage.ext_reage_dec_id ext_reage_dec_id,
ext_reage.dec_dt dec_dt,
ext_reage.ext_reage_dec_rsn_id ext_reage_dec_rsn_id,
ext_reage.ext_reage_stat_id ext_reage_stat_id,
ext_reage.mitigat_plan_type_id mitigat_plan_type_id,
ext_reage.new_mat_dt new_mat_dt
from yo.t_ext_reage ext_reage
) ext_reage_2,
t_acct_mil_svc acct_mil_svc,
t_spoc_asn_stat_lkp spoc_asn_stat,
t_lgl_pre_asn lgl_pre_asn,
(SELECT acct_id, expir_dt,chrg_off_dec_stat_id
FROM t_chrg_off_dec
WHERE (acct_id, chrg_off_dec_id) in
(SELECT acct_id, MAX(chrg_off_dec_id)
FROM t_chrg_off_dec
WHERE expir_dt > TRUNC(SYSDATE)
GROUP BY ACCT_ID)) chrg_off_dec,
t_settle_stat_lkp settle_stat,
t_settle settle
WHERE cra.cra_cd (+) = bk.cra_cd
AND zip.zip (+) = bk.zip
AND prod_lookup.prod_id (+) = bk.prod_id
AND bk.acct_id = acct.acct_id
AND agen_tran.agen_tran_id (+) = recovery_agen_evnt_a.agen_tran_id
AND bk.acct_id = recovery.acct_id(+)
AND recovery.curr_recovery_req_id = recovery_req.recovery_req_id (+)
AND recovery_settle.acct_id (+) = recovery.acct_id
AND recovery_agen_evnt_b.acct_id (+) = recovery.acct_id
AND bnkr_case.acct_id (+) = acct.acct_id
AND bnkr_case.prim_ind (+) = 1
AND recovery_agen_evnt_b.agen_tran_id = recovery_agen_evnt_a.agen_tran_id (+)
AND acct.sys_stat_id <> 6
AND acct.sor_id = 2
AND acct_ent_acct.acct_id (+) = acct.acct_id
AND acct_ent_acct.cntct_type_id (+) = 1
AND acct_ent_agen.acct_id (+) = acct.acct_id
AND acct_ent_agen.cntct_type_id (+) = 203
AND agen.ent_id (+) = acct_ent_agen.ent_id
AND acct_cltrl.acct_id (+) = acct.acct_id
AND acct_cltrl.prim_ind (+) = 1
AND acct_cltrl.cltrl_id = forcls.cltrl_id (+)
AND acct_cltrl.cltrl_id = real_estate.cltrl_id (+)
AND coll_act.acct_id (+) = acct.acct_id
AND acct_pre_queue_atr.acct_id (+) = acct.acct_id
AND acct_pre_queue_atr.acct_id (+) = acct.acct_id
AND risk_force.acct_id (+) = acct.acct_id
AND ent_summary_acct.ent_id (+) = acct_ent_acct.ent_id
AND ent_summary_agen.ent_id (+) = acct_ent_agen.ent_id
AND spcl_hdlg.acct_id (+) = acct.acct_id
AND spcl_hdlg.spcl_hdlg_stat_id (+) = 3087
AND spcl_hdlg.spcl_hdlg_stat_set_id (+) = 3087
AND dstr.acct_id (+) = acct.acct_id
AND dstr_desc_lkup.dstr_desc_id (+) = dstr.dstr_desc_id
AND dstr_impact_lvl_lkup.dstr_impact_lvl_id (+) = dstr_desc_lkup.dstr_impact_lvl_id
AND rstrc.rstrc_id (+) = rstrc_acct.rstrc_id
AND rstrc_acct.acct_id (+) = acct.acct_id
AND coll_score.acct_id (+) = acct.acct_id
AND ext_reage_2.acct_id (+) = acct.acct_id
AND ext_reage_2.rank (+) = 1
AND acct_mil_svc.acct_id (+) = acct.acct_id
AND acct_mil_svc.prim_ind (+) = 1
AND spoc_asn_stat.spoc_asn_stat_id (+) = acct.spoc_asn_stat_id
AND lgl_pre_asn.acct_id (+) = acct.acct_id
AND chrg_off_dec.acct_id (+) = acct.acct_id
AND settle_stat.settle_stat_id (+) = settle.settle_stat_id
AND settle.acct_id (+) = acct.acct_id
) T WHERE t.ln_num=1;


