
SELECT /*+ parallel (4) */ DISTINCT schema_nm, tbl_nm, prim_ky_cnt, prim_ky_1_col_nm, prim_ky_1_val_num, prim_ky_2_col_nm, prim_ky_2_val_num                                                                                                                                                                                                                                                                                                                                                                        
                                  FROM SRC_CORE2_DEAL_SPL.replication_cdc_qu_hist                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                      ,(SELECT upper(trim(regexp_substr(prpty_val_txt, '[^,]+', 1, level))) table_name                                                                                                                                                                                                                                                                                                                                                                                              
                                          FROM (SELECT prpty_val_txt                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                  FROM MDE_OPER_SPL.config_prpty                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                 WHERE appl_sys_id = 0                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                   AND appl_nm LIKE :cn_package_name                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                   AND prpty_typ_txt = :cn_function_name                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                   AND prpty_nm = 'TableList') t                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                        CONNECT BY instr(prpty_val_txt, ',', 1, level - 1) > 0) tbl                                                                                                                                                                                                                                                                                                                                                                                                                 
                                 WHERE mode_enqueue_dttm BETWEEN :lv_start_dt AND :lv_end_dt                                                                                                                                                                                                                                                                                                                                                                                                                        
                                   AND replication_cdc_qu_hist.tbl_nm = tbl.table_name                                                                                                                                                                                                                                                                                                                                                                                                                              
                                   AND replication_cdc_qu_hist.actn_txt IN ('INSERT','UPDATE')                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
