set feed on                                                                                                                                                                                                                                                                                                                                                                                                     
set echo on                                                                                                                                                                                                                                                                                                                                                                                                     
WHENEVER SQLERROR CONTINUE                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                
   CREATE USER "AWACHTER" IDENTIFIED BY VALUES 'S:3E4CDBF07AAAE998A5C8ACF3DAC2D195DA966FFB6E09DEC9C9124BBC7C71;42B71F467BD00381'                                                                                                                                                                                                                                                                                
      DEFAULT TABLESPACE "USERS"                                                                                                                                                                                                                                                                                                                                                                                
      TEMPORARY TABLESPACE "TEMP";                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
   GRANT "RESOURCE" TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT UPDATE ANY TABLE TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT INSERT ANY TABLE TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT SELECT ANY TABLE TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT CREATE TABLE TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT UNLIMITED TABLESPACE TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                
  GRANT CREATE SESSION TO "AWACHTER";                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
ERROR:
ORA-31608: specified object of type OBJECT_GRANT not found 
ORA-06512: at "SYS.DBMS_SYS_ERROR", line 86 
ORA-06512: at "SYS.DBMS_METADATA", line 3264 
ORA-06512: at "SYS.DBMS_METADATA", line 5011 
ORA-06512: at line 1 


alter user AWACHTER identified by ifmc;                                                                                                                                                                                                                                                                                                                                                                         
